Display in startup console in warning the CLI parameters that do not match the persisted config anymore
Terracotta-OSS/terracotta-platform pull request #1012
Opened 2021-06-04 20:53 UTC by mathieucarbou

Here are some examples of output that we can see in the console log at startup:

```
2021-06-04 16:23:23,871 [Thread-299] INFO org.terracotta.console - 

=================================================================================================================
Node is starting from an existing configuration directory. The following CLI parameters differ from the loaded   
configuration and have been ignored and can be removed from the CLI:                                             
 - Setting: 'name': CLI=node-1-1 vs CONFIG=foo
=================================================================================================================
```

```
2021-06-04 16:22:44,530 [Thread-84] INFO org.terracotta.console - 

=================================================================================================================
Node is starting from an existing configuration directory. The following CLI parameters differ from the loaded   
configuration and have been ignored and can be removed from the CLI:                                             
 - Setting: 'log-dir': CLI=logs vs CONFIG=logs/stripe1
 - Setting: 'metadata-dir': CLI=metadata vs CONFIG=metadata/stripe1
 - Setting: 'data-dirs': CLI=main:data-dir vs CONFIG=main:user-data/main/stripe1
 - Setting: 'offheap-resources': CLI=foo:1GB,main:512MB vs CONFIG=main:512MB,second:1GB
 - Setting: 'client-reconnect-window': CLI=10s vs CONFIG=<missing>
 - Setting: 'cluster-name': CLI=tc-cluster vs CONFIG=my-cluster
=================================================================================================================
```

2021-06-07 21:54 UTC, chrisdennis requested changes

2021-06-07 21:54 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/ConfigRepoCommandLineProcessor.java
> +
If you insist on using streams I think this is a lot clearer:
```java
cliOptions.keySet().stream()
        .map(setting -> tuple2(setting,
                tuple2OfOptionals(setting.getProperty(getContext(alternate, setting.getScope())),
                        setting.getProperty(getContext(loadedNodeContext, setting.getScope())))))
        .filter(setting -> {
          Tuple2<String, String> values = setting.getT2();
          return !Objects.equals(values.getT1(), values.getT2());
        })
        .map(mismatch -> " - Setting: '" + mismatch.getT1() + "': CLI=" + mismatch.getT2().findT1().orElse("<unavailable>") + " vs CONFIG=" + mismatch.getT2().findT2().orElse("<unavailable>") + lineSeparator())
        .reduce(String::concat).ifPresent(mismatches -> server.console(lineSeparator() + lineSeparator()
                + "=================================================================================================================" + lineSeparator()
                + "Node is starting from an existing configuration directory.                                                       " + lineSeparator()
                + "The following command-line (CLI) parameters differ from the loaded configuration.                                " + lineSeparator()
                + "They have been ignored and can be removed from the CLI.                                                          " + lineSeparator()
                + mismatches
                + "=================================================================================================================" + lineSeparator()
        ));
```
but to be honest I'm not sure streams are buying anything here. I think the following is clearer still:
```java
List<String> mismatches = new ArrayList<>();
for (Setting setting : cliOptions.keySet()) {
  Optional<String> fromCli = setting.getProperty(getContext(alternate, setting.getScope()));
  Optional<String> fromRepo = setting.getProperty(getContext(loadedNodeContext, setting.getScope()));
  if (!fromCli.equals(fromRepo)) {
    mismatches.add(" - Setting: '" + setting + "': CLI=" + fromCli.orElse("<unavailable>") + " vs CONFIG=" + fromRepo.orElse("<unavailable>") + lineSeparator());
  }
}
if (!mismatches.isEmpty()) {
  server.console(lineSeparator() + lineSeparator()
          + "=================================================================================================================" + lineSeparator()
          + "Node is starting from an existing configuration directory.                                                       " + lineSeparator()
          + "The following command-line (CLI) parameters differ from the loaded configuration.                                " + lineSeparator()
          + "They have been ignored and can be removed from the CLI.                                                          " + lineSeparator()
          + String.join(lineSeparator(), mismatches) + lineSeparator()
          + "=================================================================================================================" + lineSeparator());
}
```
I've extracted a utility method here... but this should probably go on the `Scope` enum:
```java
private static PropertyHolder getContext(NodeContext alternate, Scope scope) {
  switch (scope) {
    case NODE:
      return alternate.getNode();
    case STRIPE:
      return alternate.getStripe();
    case CLUSTER:
      return alternate.getCluster();
  }
  throw new AssertionError();
}
```

2021-06-07 23:31 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/ConfigRepoCommandLineProcessor.java
> +
I definitely started my stream with the wrong set of data ;-)
I took your ideas and changes things a bit, kept `unspecified` because this is really what it means - not unavailable because a setting can be available (resolved) but not specified (configured).

2021-06-08 21:20 UTC, chrisdennis approved these changes

2021-06-08 21:20 UTC, chrisdennis commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/NodeContext.java
> +  public PropertyHolder getObject(Scope scope) {
Why not convert this switch over an enum to a dynamic dispatch on the enum?

2021-06-08 21:32 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/NodeContext.java
> +  public PropertyHolder getObject(Scope scope) {
Because I don't like that the enum class depends on NodeContext, Node, Cluster, etc...

2021-06-08 21:34 UTC, merged