New Apis for offheap usage listeners.
Terracotta-OSS/terracotta-platform pull request #1034
Opened 2021-07-27 12:02 UTC by mobasherul

2021-07-27 23:03 UTC, chrisdennis requested changes

2021-07-27 23:03 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.put(listenerUUID, new OffHeapUsageListener(threshold, consumer));
Surely you mean `putIfAbsent(...)` here?

2021-07-27 23:03 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.remove(listenerUUID);
Should this have a different behavior if the mapping is present vs if it is absent?

2021-07-27 23:03 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapUsageEventImpl.java
> +  private final float occupancy;
Isn't `occupancy` just a simple bit of FPU calc from the other values? Can't you just define a default implementation?

2021-07-27 23:03 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +  public void addUsageListener(UUID listenerUUID, float threshold, Consumer<OffHeapUsageEvent> consumer) {
Shouldn't this take a rising/falling type?

2021-07-28 06:20 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +        if (!offHeapUsageListener.isFired() && offHeapUsageListener.getThreshold() < occupancy) {
I did that for scenarios in which threshold is 0.7f rising and it send the event for the first time when it crosses 0.7f but when it will not send the event for subsequent reserve for offheap as it already has sent the event .

2021-07-28 06:24 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +  public void addUsageListener(UUID listenerUUID, float threshold, Consumer<OffHeapUsageEvent> consumer) {
It doesn't require it. It will send the rising/ falling event and on client side I will check what is the actual listner type registered.

2021-07-28 06:30 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.remove(listenerUUID);
If it is absent it will be caught on client side early and exception will be thrown.

2021-07-30 11:42 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.put(listenerUUID, new OffHeapUsageListener(threshold, consumer));
I want the listener to be re registered in case of application reconnect since I will be sending those listeners with same UUID during reconnect. I am doing this to ensure that if some events have been missed during reconnect I am registering new listener and these listeners will send the events if further reserve/free call happens as the flag has not been set for these listeners.

2021-08-18 21:32 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.put(listenerUUID, new OffHeapUsageListener(threshold, consumer));
Okay, but how do you know the difference between a re-registration and a UUID collision? The caller might know if he expects a "re-registration" but this code doesn't. I guess I don't understand how the offheap resource should have to care about any of that. If you want to know if there is a listener registered there then at least have it return the old listeners do that the caller can check what happened and behave accordingly.

2021-08-18 21:33 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.remove(listenerUUID);
Right... but this API needs to look sane on it's own. Otherwise you're practicing building brittle APIs. Just define a sane behavior for failure to remove and implement it.

2021-08-18 21:34 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +  public void addUsageListener(UUID listenerUUID, float threshold, Consumer<OffHeapUsageEvent> consumer) {
Right, but you're defining an API on an actual API here right? Why not do it right here as well?

2021-08-18 21:36 UTC, chrisdennis approved these changes
There are some sharp edges here still, but it seems like it should function okay.

2021-08-18 22:05 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourcesProvider.java
> -              attrs.put("oldThreshold", String.valueOf(update.old));
Is it safe to just change this API? Why can't we preserve the attributes and not have to also change the consumer side?

2021-08-18 22:06 UTC, chrisdennis approved these changes

2021-08-19 07:02 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +  public void addUsageListener(UUID listenerUUID, float threshold, Consumer<OffHeapUsageEvent> consumer) {
Because the listener registered here have to send both rising and falling event for specific threshold  irrespective of whether the listener is rising/falling one.

2021-08-19 13:56 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourcesProvider.java
> -              attrs.put("oldThreshold", String.valueOf(update.old));
Earlier it was used to verify it is rising/falling which is not required anymore and the stuff displayed on tmc does not get affected as well so I removed it.

2021-08-19 13:57 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.remove(listenerUUID);
will make it throw exception for sanity of this API

2021-08-19 15:50 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    listenerMap.put(listenerUUID, new OffHeapUsageListener(threshold, consumer));
There is no differentiation between normal listener registation and the listeners getting registered as part of client reconnect.Also old listeners are of no use since they contain reference to old client descriptors. UUID collision came to my mind as well but jdk provides enough guarantee that it will not happen atleast for this usecase.

2021-08-23 13:36 UTC, chrisdennis approved these changes

2021-08-23 13:36 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    if (!listenerMap.containsKey(listenerUUID)) {
Why not just use the `listenerMap.remove(...)` return value?

2021-08-23 14:01 UTC, mobasherul commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    if (!listenerMap.containsKey(listenerUUID)) {
Its not doing anything after removal.

2021-08-23 14:10 UTC, chrisdennis commented on offheap-resource/src/main/java/org/terracotta/offheapresource/OffHeapResourceImpl.java
> +    if (!listenerMap.containsKey(listenerUUID)) {
`listenerMap.remove(uuid) == null` is exactly the same as `containsKey()`.

2021-08-24 15:31 UTC, merged