Fix deadlock when a nomad transaction is committed through the Nomad entity at the same time a diagnostic call is made querying the state of the configuration system
Terracotta-OSS/terracotta-platform pull request #1035
Opened 2021-07-27 14:23 UTC by mathieucarbou

2021-07-27 20:49 UTC, chrisdennis requested changes

2021-07-27 20:49 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +          || node.getInternalAddress().equals(me.getInternalAddress())
Why do we match on anything beyond UID?

2021-07-27 20:49 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +  private volatile NodeContext upcomingNodeContext;
If these are guarded by the lock why are they volatile? Is Findbugs trying to tell you something?

2021-07-28 12:26 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +        LOGGER.info("No license installed");
Yes, we can uninstall the license (remove it) if parameter is null

2021-07-28 12:29 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +        LOGGER.info("No license installed");
This line was there to confirm that there is no license installed. I will move it down a little.

2021-07-28 12:43 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +    if (licenseLock.readLock().tryLock()) {
I have converted it to a normal read lock/unlock, it's totally fine and better. Reading the license is done when doing a DS operation to setup the new stripe. In theory, there couldn't be any other license installation process at the same time since DC is supposed to be locked.

2021-07-28 12:44 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +      return upcomingNodeContext.clone();
Yes: the DC model implements that to return a copy of the topology for the callers because it is not immutable.

2021-07-28 12:48 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +      this.runtimeNodeContext = upcomingNodeContext;
That line is OK.

But thanks because there was a bug: `return upcomingNodeContext;` shouldn't have been with the if.

This the method called when installing the pushed topology when nodes are being configured (import) or activated. So at this time the runtime topology is equal to the upcoming topology. In case of activation, there will be a restart after Nomad gets acttivated.

2021-07-28 12:52 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +          || node.getInternalAddress().equals(me.getInternalAddress())
UIDs are internal settings hidden to the user except when he exports a config from a cluster. The user never has to set these. There are some commands allowing a user to push a new topology anmd we need to detected where is our node inside it.

2021-07-28 12:53 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +  private volatile NodeContext upcomingNodeContext;
No, it's me that didn't remove it because the fields were moved from the old class to the new one without being updated.

2021-07-28 17:01 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +          tempFile = Files.createTempFile("terracotta-license-", ".xml");
done

2021-07-28 19:40 UTC, chrisdennis approved these changes
Approved. Feel free to act on my remaining comments (or not).

2021-07-28 19:40 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +  @SuppressWarnings("NonAtomicOperationOnVolatileField")
This should be unnecessary now.

2021-07-28 19:40 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +          || node.getInternalAddress().equals(me.getInternalAddress())
Okay... but is the effect we want here more like:
1. If there is a UID match... take that.
2. If there isn't a UID match look for a **unique** name match.
3. If there isn't a UID or name match look for a **unique** internal address match.

2021-07-28 19:40 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +  @SuppressWarnings("NonAtomicOperationOnVolatileField")
No longer needed right?

2021-07-28 19:40 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +        LOGGER.info("No license installed");
Maybe I'm laboring the point... what was more getting at is that the voice/tense is wrong.

"License installation successful" vs "No license installed".

The former reports the success of an operation... the later asserts a state.

2021-07-28 19:40 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +      return licenseFile.toFile().exists() && Files.isRegularFile(licenseFile) && Files.isReadable(licenseFile);
`exists()` is redundant here.

2021-07-28 19:40 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +      return upcomingNodeContext.clone();
I assume we have no immutable implementation we can convert to?

2021-07-28 20:30 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +      return upcomingNodeContext.clone();
no...

2021-07-28 20:34 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +          || node.getInternalAddress().equals(me.getInternalAddress())
no because names could be auto-generated but internal address is more reliable since it is less likely to change and is auto-generated.
I.e. in configuration mode, when a node starts, UID and name are generated. If a user pushes a topology to this node, the more reliable information there to match is the internal address.

2021-07-28 20:34 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +  @SuppressWarnings("NonAtomicOperationOnVolatileField")
thanks!

2021-07-28 20:35 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Topologies.java
> +  @SuppressWarnings("NonAtomicOperationOnVolatileField")
thanks!

2021-07-28 20:44 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +        LOGGER.info("No license installed");
Yes, I completely agree... But updating that requires to go over some test (changes current behavior).
So I have updated the PR to include this update.
- if parameter not null => `"License installation successful"`
- if license installed and parameter is null => `"License removal successful"`
- if license not installed and parameter is null => `"No license installed"`

2021-07-29 13:43 UTC, merged