Passive redirection should consider the topology configuration to redirect to the right active endpoint
Terracotta-OSS/terracotta-platform pull request #1043
Opened 2021-09-23 21:05 UTC by mathieucarbou

Implementation of a `NetworkTranslator` for 10.x that will correctly pick the right endpoint for the active node when a passive sends a redirection back to a client.

A terracotta cluster is either meant to be used with all the clients in the same network as the nodes (one network for all services), or, if isolated, a terracotta cluster can be configured to have all its nodes in an isolated network, with public hostnames and ports configured for all nodes. In that case, the isolated network is dedicated for TC nodes and all clients have to connect by using the public hostnames/port from outside.

The `NetworkTranslator` was always returning the "internal" endpoint of the active server, which of course is not accessible from clients outside an isolated "terracotta network", which could prevent them from connecting to the cluster.

This fix works this way:
- If a public hostname/port is configured for the active node, it will be returned
- otherwise, the normal hostname/port is returned

CC @ tglaeser

2021-10-14 13:32 UTC, chrisdennis requested changes

2021-10-14 13:32 UTC, chrisdennis commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Cluster.java
> +        .map(stripe -> stripe.findNode(addr).orElse(null))
Would this be better expressed as:
```java
stripes.stream().map(stripe -> stripe.findNode(addr)).filter(Optional::isPresent).map(Optional::get).findFirst()
```

2021-10-14 13:32 UTC, chrisdennis commented on dynamic-config/server/services/pom.xml
> +      <groupId>org.terracotta.internal</groupId>
I know Myron was pushing to have less dependency on internal artifacts coming out of core. Is this something we could eliminate?

2021-10-14 13:32 UTC, chrisdennis commented on dynamic-config/server/services/src/main/java/org/terracotta/dynamic_config/server/service/DynamicConfigNetworkTranslator.java
> +      // there is a bug in core. Core that does support Ipv6 addresses correctly.
You mean core *doesn't* support IPv6 correctly? Is there an issue to reference so that:
* this workaround can get removed when fixed
* the correctness of this code can be judged.

2021-10-14 13:32 UTC, chrisdennis commented on dynamic-config/server/services/src/main/java/org/terracotta/dynamic_config/server/service/DynamicConfigServiceProvider.java
> +    if (configuration.getServiceType() == NetworkTranslator.class) {
Why is this service the only service that needs special-casing?

2021-10-14 13:37 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Cluster.java
> +        .map(stripe -> stripe.findNode(addr).orElse(null))
it's the same :P mine is just 1 line less and 9 characters less to type.

2021-10-14 13:44 UTC, mathieucarbou commented on dynamic-config/server/services/src/main/java/org/terracotta/dynamic_config/server/service/DynamicConfigNetworkTranslator.java
> +      // there is a bug in core. Core that does support Ipv6 addresses correctly.
Updated the comment (to match the commit comment).
Core is using such hacks also at some places too. This is due to the fact that core does not provide a way to represent a hostname/port combination (what we talked about) so everything goes through string, but the string representation of an `ip:port` is not the same for IPv4 and v6 and also changes across JVMs.

2021-10-14 13:47 UTC, mathieucarbou commented on dynamic-config/server/services/src/main/java/org/terracotta/dynamic_config/server/service/DynamicConfigServiceProvider.java
> +    if (configuration.getServiceType() == NetworkTranslator.class) {
Because `findService()` looks at the DC services (provided at bootstrap time) that are exposed inside `PlatformConfiguration` and made available to services when they get initialized (and entities through this SP).
`NetworkTranslator` is a core interface looked up by core - aka what is done for SSL buffers.

2021-10-14 16:24 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Stripe.java
> +    return nodes.stream().filter(node -> node.hasAddress(addr)).findFirst();
What do you mean ? This is the configured topology by the user: this method tries to find the node matching the host/port as configured by the user.

Why would I check the bind address ?

2021-10-14 16:32 UTC, myronkscott commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Stripe.java
> +    return nodes.stream().filter(node -> node.hasAddress(addr)).findFirst();
the redirect address is the address that the server is available to clients on.  If the bind address is a distinct interface or address, the server publishes that address.  If the bind address is wildcard, the combination of the hostname and port is published.

2021-10-14 19:59 UTC, myronkscott commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Stripe.java
> +    return nodes.stream().filter(node -> node.hasAddress(addr)).findFirst();
yes

2021-10-14 23:28 UTC, mathieucarbou commented
@myronkscott @chrisdennis : so after discussions I have updated this PR to account for the bind address when not a wildcard one.

But we also settled on not merging this PR yet. but instead group it with other fixes / discussions about hostname / bind addr

2021-10-15 10:44 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Cluster.java
> +        .map(stripe -> stripe.findNode(addr).orElse(null))
> Not quite the same... yours assumes that `findNode(...)` never returns null.
Same for yours: `.filter(Optional::isPresent)` would throw a NPE

2021-10-19 14:40 UTC, merged