Periodic logging about resource usage
Terracotta-OSS/terracotta-platform pull request #1049
Opened 2021-10-08 16:10 UTC by mobasherul

2021-10-08 21:11 UTC, chrisdennis requested changes
It seems to me that what is being logged here is a generally valuable metric (that might want to be exposed in any M&M view). It also seems like there are many metrics that might be valuable to customers if periodically logged. With those statements in mind I'm thinking it makes more sense to frame this feature as the periodic logging of some monitorable metrics. In that sense the engine that drives this should probably be integrated with the M&M code. That would also prevent us from spawning two extra threads where each thread just logs a single line every 5 minutes.

2021-10-11 09:58 UTC, mathieucarbou commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/DataDirsConfigImpl.java
> +  });
This is not the right place to put a thread pool since this is only a configuration holder class.
Any action / computation should much more happen through a service.
I.e. in M&M we have a service tht has a singleton thread pool with one thread to handle stat collection. Services have access to configs so it would be possible to re-use the existing M&M services to do this sort of logging.

2021-10-12 17:33 UTC, mobasherul commented
> It seems to me that what is being logged here is a generally valuable metric (that might want to be exposed in any M&M view). It also seems like there are many metrics that might be valuable to customers if periodically logged. With those statements in mind I'm thinking it makes more sense to frame this feature as the periodic logging of some monitorable metrics. In that sense the engine that drives this should probably be integrated with the M&M code. That would also prevent us from spawning two extra threads where each thread just logs a single line every 5 minutes.

M&M code have their thread pools which do statistics collection but only when tmc is connected to tms otherwise M&M code doesn't do anything.

2021-10-12 17:35 UTC, mobasherul commented
Closing this in favor of https://github.softwareag.com/Terracotta/terracotta-enterprise/pull/170 as I am creating service provider which will take care of logging

2021-10-12 17:35 UTC, closed without merging