TDB-5488 - fix set/unset license-file when unconfigured
Terracotta-OSS/terracotta-platform pull request #1060
Opened 2021-12-10 19:51 UTC by tmesic99

Fix for defect: https://itrac.eur.ad.sag/browse/TDB-5488.
This problem started after 10.7 fix 3, resulting from a change to when a server's config folders get created on disk (698072a0).  With 10.7 fix 3 and earlier, config folders were created when the node was unconfigured .  But this behavior was changed to only create the config folder structure as part of activation.  This problem revealed itself when setting a license file on an unconfigured node with the server attempting to install the license into a non-existent folder throwing an exception (see TDB-5488).

The solution here holds the supplied 'licenseContent' string in memory, if set when unconfigured, until the node is activated.  Upon activation, the existing licenseContent is then used to create the license on disk.  Or, that in-memory license is superseded if the license is optionally supplied with the activate call.

2021-12-13 14:42 UTC, mathieucarbou requested changes
@tmesic99 I am wondering if this is the right way to solve this issue...

In `Setting`:

`when(CONFIGURING, ACTIVATED).allow(SET, UNSET).atLevel(CLUSTER)`

makes no sense because from a UX perspective, an un-configured node is "nothing" so it's completely useless to license it Besides, there is no "folder" yet to write it.

When doing an activation, a consistency check amongst the nodes is done. But the license is not part of this check. Besides, this is a file that the user could remotely change when activated, but also just update locally in config folder.

Licensing needs to be done 24 hours max after activation (or before a cache or store client connects). So there is no rush in doing it early in the process.

So I am wondering if we should just set the validation to:

`when(CONFIGURING).allow(SET, UNSET).atLevel(CLUSTER)`

And then add some validations in the CLI instead, plus on the backend side (to throw if a license install is requested, but the config/license folder does not exist yet).

2021-12-13 15:07 UTC, tmesic99 commented
> 

@mathieucarbou Yes, I had the exact same thoughts.  I opted for the solution I implemented in this PR because it preserves the behavior that's always been present in dynamic config.  That is, users have always been able to pre-configure their license before activation.  But if you prefer to take the approach of altogether removing the ability to set/unset licenses from CONFIGURED nodes, then that's fine.  Is that how you'd like to proceed?

2021-12-13 15:50 UTC, mathieucarbou commented
> > 
> 
> @mathieucarbou Yes, I had the exact same thoughts. I opted for the solution I implemented in this PR because it preserves the behavior that's always been present in dynamic config. That is, users have always been able to pre-configure their license before activation. But if you prefer to take the approach of altogether removing the ability to set/unset licenses from CONFIGURED nodes, then that's fine. Is that how you'd like to proceed?

No, that's right... I have checked the code and saw that the `set` was allowed since a while... :-(

Let's fix it like that...

2021-12-13 16:58 UTC, mathieucarbou requested changes

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +  private String licenseContent;
field should be `volatile`

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +  public void install(String licenseContent, Cluster cluster, boolean isActive) {
~~I would rename `isActive` to `nomadReady` (or something equivalent), because the installation does not require the server to be active, but only folders to be there.~~

Actually, you can remove this boolean and use the `NomadManager.nomadMode()` call (see other comment)

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +      }
I would be very careful there and only use this hack when in un-configured mode. Because when the server is activated, we really don't want this class field to be set, otherwise the getter method might return the value in case the user removed the license file from the disk. The value will be kept in memory and the server might still  licensed, when it's not anymore.

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +  private String licenseContent;
I would rename it to something more meaningful like: `temporaryLicenseContent` or a better name, wit ha comment saying that this field is ONLY in unconfigured mode

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +  private String licenseContent;
Note: you could change the ctor of `Licensing` to have a ref inside of the `NomadServerManager`, to know the state of nomad with NomadServerManager.getNomadState(): RW == nomad system is up & running, we can do nomad changes. RO == unconfigured mode or repair.

`this.licensing = new Licensing(licenseService, nomadServerManager.getConfigurationManager());`

For the licensing stuff, there no notion of activated or not. The only concept to consider is whether the nomad system is RW or RO to be able to write or not the license file.

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +    if (!content.isPresent() && licenseContent != null) {
I would check the nomadMode here too.

2021-12-13 16:58 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +      }
You can use the `NomadManager.nomadMode()` to protect this

2021-12-14 08:50 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +    if (!content.isPresent() && licenseContent != null) {
perhaps a method like that would help:

```java
private Optional<String> findTemporarySetLicense() {
    return nomadManager.getNomadMode() == RW && temporaryLicense != null ? Optional.of(TemporaryLicense) : Optional.emopty();
}
```

Then `getLicenseContent()` would become something like:

```java
return Optional.ofNullable(read().orElseGet(() -> findTemporarySetLicense().orElse(null));
```

2022-01-05 13:57 UTC, tmesic99 commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +  private String licenseContent;
done

2022-01-05 13:57 UTC, tmesic99 commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +  public void install(String licenseContent, Cluster cluster, boolean isActive) {
done

2022-01-05 13:57 UTC, tmesic99 commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +      }
done

2022-01-05 13:57 UTC, tmesic99 commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +    if (!content.isPresent() && licenseContent != null) {
done

2022-01-05 14:45 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +   * If install is called when the server is ACTIVE (RW mode), we use the license that was supplied during activation.
_when the server is **configured** (RW mode)_

2022-01-05 14:46 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/Licensing.java
> +        // server is Active
_server is Active_ => _server is **configured**_

2022-01-05 14:52 UTC, mathieucarbou approved these changes

2022-01-05 19:31 UTC, merged