Change kit
Terracotta-OSS/terracotta-platform pull request #1100
Opened 2022-06-29 17:39 UTC by myronkscott

Change the kit to be purely additive to the core kit.  We should not repackage the core kit as the platform components can be exploded on top of the core kit version.  This should make updating core in downstream projects not directly dependent on platform update and rebuild.

2022-06-29 19:28 UTC, mathieucarbou commented
thanks for removing the clustered map :P

2022-06-29 19:32 UTC, mathieucarbou requested changes

2022-06-29 19:32 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/pom.xml
> +                </artifactItem>
Why do the system tests (that ideally would treat a product as a near black box thing) need to know what to include / exclude from a kit dependency ?

Could we put that outside so that system tests only have ot point to 1 artifact to test ?

2022-06-29 19:32 UTC, mathieucarbou commented on management/testing/integration-tests/pom.xml
> +                </artifactItem>
same question, solving it would remove this code duplication

2022-06-29 19:53 UTC, myronkscott commented on dynamic-config/testing/system-tests/pom.xml
> +                </artifactItem>
the core kit will not include these things in the next release.  I can remove these excludes at that point.

2022-06-29 20:03 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/pom.xml
> +                </artifactItem>
That's why they were removed initially in platform-kit.xml, because this was the common point ;-) 

platform-kit.xml was acting as a bridge between the kit+plugins we want tt test, excluding the things we don't want from core.

2022-08-08 20:29 UTC, myronkscott commented on dynamic-config/testing/system-tests/pom.xml
> +                </artifactItem>
excludes have been removed

2022-08-11 02:18 UTC, myronkscott commented
These changes are confirmed to work in ehcache3 and EE is unaffected.

2022-10-19 19:08 UTC, mathieucarbou commented on diagnostic/client/pom.xml
> +      <scope>provided</scope>
What is the reason already why a required transitive dependency of a normal library used client -side which is not a server plugin would be provided ?

Does it mean everywhere in every module slf4j has to be provided now ?

2022-10-19 19:08 UTC, mathieucarbou commented on dynamic-config/cli/cli-support/pom.xml
> +      <scope>provided</scope>
What is the reason already why a required transitive dependency of a normal library used client -side which is not a server plugin would be provided ?

Does it mean everywhere in every module logging has to be provided now ? Why ? And why not the other dependencies?

2022-10-19 19:08 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/pom.xml
> +      <scope>provided</scope>
Same question

2022-10-19 19:08 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/pom.xml
> +      <scope>test</scope>
Same question

2022-10-19 19:08 UTC, mathieucarbou commented on dynamic-config/pom.xml
> +      <scope>provided</scope>
Why?

2022-10-19 19:08 UTC, mathieucarbou commented on management/nms-agent-entity/nms-agent-entity-client/pom.xml
> +      <scope>provided</scope>
Why ? This is a normal library, used client -side which has a transitive dep requires to work...

2022-10-19 19:08 UTC, mathieucarbou commented on voltron-proxy/voltron-proxy-client/pom.xml
> +    </dependency>
Why ? It's client side

2022-10-19 19:23 UTC, myronkscott commented on diagnostic/client/pom.xml
> +      <scope>provided</scope>
If we don't do this, the api jar gets pulled into the kit too many places.  If you are using this, it is in the context of some form of the client-runtime which also pulls slf4j and any other logging support.

2022-10-19 19:24 UTC, myronkscott commented on dynamic-config/cli/cli-support/pom.xml
> +      <scope>provided</scope>
see above

2022-10-19 19:31 UTC, myronkscott commented on diagnostic/client/pom.xml
> +      <scope>provided</scope>
We rely on connection-api and slf4j-api for compile but the runtime implementation and linking is determined elsewhere.

2022-10-19 21:16 UTC, mathieucarbou commented on diagnostic/client/pom.xml
> +      <scope>provided</scope>
oh I remember the discussion yes. And this only applies to entity clients.

2022-10-19 21:17 UTC, mathieucarbou approved these changes

2022-10-19 21:18 UTC, merged