Refreshable Endpoints
Terracotta-OSS/terracotta-platform pull request #1142
Opened 2022-11-14 23:34 UTC by mathieucarbou

2022-11-17 13:28 UTC, mathieucarbou commented
rebased

2022-11-17 14:20 UTC, chrisdennis requested changes

2022-11-17 14:20 UTC, chrisdennis commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  private Stream<Node.Endpoint> endpoints() {
If we also add:
```java
private Stream<Node.Endpoint> endpoints(UID stripeUID) {
  return cluster.getStripe(stripeUID).map(s -> s.getNodes().stream().map(node -> node.determineEndpoint(endpointType))).orElse(Stream.empty());
}
```
then we. can switch to:
```java
public Iterable<InetSocketAddress> asInetSocketAddresses() {
  return () -> endpoints().map(e -> e.getHostPort().createInetSocketAddress()).iterator();
}

public Iterable<HostPort> asHostPorts() {
  return () -> endpoints().map(Node.Endpoint::getHostPort).iterator();
}

public Iterable<InetSocketAddress> asInetSocketAddresses(UID stripeUID) {
  return () -> endpoints(stripeUID).map(e -> e.getHostPort().createInetSocketAddress()).iterator();
}

public Iterable<HostPort> asHostPorts(UID stripeUID) {
  return () -> endpoints(stripeUID).map(Node.Endpoint::getHostPort).iterator();
}
```

2022-11-17 14:20 UTC, chrisdennis commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  public Endpoints(Cluster cluster, EndpointType endpointType) {
There seems to be some confusion between the set of constructors exposed here and the set of methods available on `Cluster`. I'm thinking it might be cleaner to rationalize this just this constructor here, and lean on the methods in Cluster for the rest?

2022-11-17 14:20 UTC, chrisdennis commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Cluster.java
> +    return new Endpoints(this, initiator.getEndpointType());
Perhaps 
```java
return determineEndpoints(initiator.getEndpointType());
```
?

2022-11-17 14:22 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  private final AtomicReference<Cluster> cluster = new AtomicReference<>();
In our use case when in a callback thread from core, yes, but should we limit to this only use case ?

2022-11-17 14:28 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  private Stream<Node.Endpoint> endpoints() {
thanks! far easier lol!

2022-11-17 14:33 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  public Endpoints(Cluster cluster, EndpointType endpointType) {
yes we can do that, That is tricky otherwise for the mind. But it will make callers do more stuff also. I wanted to simplify the usages fro callers because they can call the ctors directly.

2022-11-17 14:46 UTC, chrisdennis commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  private final AtomicReference<Cluster> cluster = new AtomicReference<>();
The semantics of an atomic set and a volatile write are the same.

> The memory effects for accesses and updates of atomics generally follow the rules for volatiles, as stated in The Java Language Specification (17.4 Memory Model) :
> * get has the memory effects of reading a volatile variable.
> * set has the memory effects of writing (assigning) a volatile variable.

2022-11-17 14:55 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Endpoints.java
> +  private final AtomicReference<Cluster> cluster = new AtomicReference<>();
Oh !!! I didn't know... But it makes sense. Sorry!

2023-01-04 15:48 UTC, chrisdennis approved these changes

2023-01-04 16:59 UTC, merged