Jackson => Gson (2/2)
Terracotta-OSS/terracotta-platform pull request #1183
Opened 2023-06-29 18:40 UTC by mathieucarbou

2023-07-12 17:19 UTC, mathieucarbou commented
moving to draft - refactoring of how the `GsonModule` works internally.

2023-07-12 20:49 UTC, GaryWKeim commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/PathTypeAdapter.java
> +    for (Path segment : value) {
Wondering why this is a for-loop.

2023-07-12 20:49 UTC, GaryWKeim commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ClusterFactoryTest.java
> -  @Test
NM: I see that they moved to a different class.

2023-07-13 08:44 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/UnsafeObjectTypeAdapterFactory.java
> + * Since deserialization requires to load a class, this adapter is unsafe and should only be
You have an example in `DiagnosticJsonModule`.
Gson is strongly types and does not allow the serialisation of an object if it cannot deserialise. And it uses the declared types to determine how to deserialise. 
But some classes do not declare types (ie. raw collections, raw types like Object or Object[]). 
For such cases, jackson was automatically appending the `@class` information next to the serialised data and was doing a classloader call when deserialising.
Gson does not support this, because is prevents serialising something "unknown", and does not support class loading (one of the reason why there is so few security issues with Gson).
So this class allows to mark some types or annotated fields on mixins to support adding the class information next to the serialised object exactly like Jackson was doing.

2023-07-13 09:53 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/HierarchyTypeAdapterFactory.java
> + * These extra classes are not available in any Maven repo and are meant as samples to be copied and adapter.
true! that wasn't the case at first but I had to...

2023-07-13 09:54 UTC, mathieucarbou commented on management/testing/integration-tests/src/test/java/org/terracotta/management/integration/tests/ServerCacheManagementIT.java
> +      System.out.println(toJson(stats));stats.get(0);
sout removed - was there to debug the incoming data

2023-07-13 09:57 UTC, mathieucarbou commented on dynamic-config/server/configuration-repository/src/test/java/org/terracotta/dynamic_config/server/configuration/nomad/persistence/DefaultHashComputerTest.java
>  public class DefaultHashComputerTest {
Dic and spell check says computer ?
https://www.askdifference.com/computor-vs-computer/

2023-07-13 09:57 UTC, mathieucarbou commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ClusterFactoryTest.java
> -  @Test
yes nothing was removed ;-)

2023-07-13 10:01 UTC, mathieucarbou commented on dynamic-config/json/src/main/java/org/terracotta/dynamic_config/api/json/DynamicConfigJsonModule.java
> +    // These are all the DC classes allowed when serializing Class type ot deserializing @class marker into an object for unknown declared types.
done

2023-07-13 10:03 UTC, mathieucarbou commented on common/sanskrit/src/test/java/org/terracotta/persistence/sanskrit/json/TestModule.java
> +        .withSubtype(TestData.CookingManual.class)
ahah! good catch! my mistake!

2023-07-13 10:03 UTC, mathieucarbou commented on common/json-support/src/test/java/org/terracotta/json/SerializationTest.java
> +  public void test_any_subtyoes() {
fixed

2023-07-13 10:05 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/PathTypeAdapter.java
> +    for (Path segment : value) {
How would you do it otherwise ? The goal here is to write all the path segments within an array using the streaming api for Gson.

2023-07-13 17:39 UTC, GaryWKeim commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/HierarchyTypeAdapterFactory.java
> + * These extra classes are not available in any Maven repo and are meant as samples to be copied and adapter.
I meant that the comment says "copied and adapter"

2023-07-13 17:41 UTC, GaryWKeim commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/PathTypeAdapter.java
> +    for (Path segment : value) {
I see, it's `Path.iterator`.. subtle.

2023-07-13 17:43 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/HierarchyTypeAdapterFactory.java
> + * These extra classes are not available in any Maven repo and are meant as samples to be copied and adapter.
Yeah, a Path is an Iterable, weirdly

2023-07-13 17:46 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/PathTypeAdapter.java
> +    for (Path segment : value) {
Yeah, a Path is an Iterable, weirdly

2023-07-13 19:33 UTC, chrisdennis requested changes

2023-07-13 19:33 UTC, chrisdennis commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/HierarchyTypeAdapterFactory.java
> +/*
This needs to have the original Google copyright and license header. We can add ours in addition to cover our additions... but the original needs to be there.

2023-07-13 19:33 UTC, chrisdennis commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/MixinTypeAdapterFactory.java
> + * This Gson adapter is highly inspired from
Probably needs the original Google copyright header to be safe here then.

2023-07-13 19:33 UTC, chrisdennis commented on common/json-support/src/main/java/org/terracotta/json/gson/UnsafeObjectTypeAdapterFactory.java
> +  private <E> JsonElement serializeArray(Gson gson, TypeToken<E> token, Object value) {
Generic typing seems wrong here... `E` is doing double duty as both the array type and the component type.

2023-07-13 19:33 UTC, chrisdennis commented on common/nomad/src/main/java/org/terracotta/nomad/messages/TakeoverMessage.java
> +  TakeoverMessage() {
Why... what's this for, and how is GSon initializing the fields? Reflection?

2023-07-13 19:33 UTC, chrisdennis commented on diagnostic/common/src/main/java/org/terracotta/diagnostic/common/json/DiagnosticJsonModule.java
> +    config.registerMixin(DiagnosticResponse.class, DiagnosticResponseMixin.class);
What happened to the `DiagnosticRequestMixin`?

2023-07-13 19:33 UTC, chrisdennis commented on dynamic-config/testing/system-tests/src/test/resources/logback-ext-test.xml
> +    <logger name="org.terracotta.dynamic_config" level="TRACE"/>
Did you intend to commit these?

2023-07-13 19:33 UTC, chrisdennis commented on dynamic-config/testing/system-tests/src/test/resources/logback-test.xml
> +  <logger name="org.terracotta.dynamic_config" level="TRACE" additivity="false">
Did you intend to commit these?

2023-07-13 19:33 UTC, chrisdennis commented on pom.xml
> +        <version>2.10.1</version>
Should GSon get a version property?

2023-07-13 20:01 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/HierarchyTypeAdapterFactory.java
> +/*
Ok!

2023-07-13 20:03 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/MixinTypeAdapterFactory.java
> + * This Gson adapter is highly inspired from
Ok!
Note: This one is a pretty big adaptation of the original class.

2023-07-13 20:04 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/NullTypeAdapter.java
> +    out.jsonValue("null");
No because the value will of type Class<T> ( a type we want to use as a way to force null)

2023-07-13 20:05 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/internal/HierarchyTypeAdapterFactory.java
> +/*
I will add their license in another class too (runtime type adapter).

2023-07-13 20:09 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/Adapters.java
> +        float n = Float.parseFloat(value);
I agree with you... This is something all parsers do : they make a choice. I will look but if I remember I am reproducing here what Gonna or Jackson is doing. 
There might be a way to avoid that with the lazy number class of Gson. I will check.

2023-07-13 20:17 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/Adapters.java
> +          || Collection.class.isAssignableFrom(type.getRawType())
ah! missed that one :P

2023-07-13 20:20 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/UnsafeObjectTypeAdapterFactory.java
> +  private <E> JsonElement serializeArray(Gson gson, TypeToken<E> token, Object value) {
Crap yes there is a mistake. 
E is the array element type. So it should be `TypeToken<?> token` instead.

2023-07-13 20:25 UTC, mathieucarbou commented on common/nomad/src/main/java/org/terracotta/nomad/messages/TakeoverMessage.java
> +  TakeoverMessage() {
Yeah, see my comments in the PR... 

Gson being totally field based and reflection based, for classes we control, it requires to be able to call a no-arg ctor, or to provide some class instanciators, which are sort of factories were we call the existing ctors with dummy values and gson takes the instance and then replace the field values. Which is as ugly and requires more code than just adding a private ctor to our classes like that...

That's one of the little price to pay for using Gson (one or the other solution above). I prefer setting private ctors because for some cases this is even not possible to instantiate with dummy values.

2023-07-13 20:27 UTC, mathieucarbou commented on diagnostic/common/src/main/java/org/terracotta/diagnostic/common/json/DiagnosticJsonModule.java
> +    config.registerMixin(DiagnosticResponse.class, DiagnosticResponseMixin.class);
We don't need anymore, like a bunch of other mixins.

`registerUnsafeTypeAdapters(Object[].class)` makes sure that Gson wraps the unknown objects inside with their runtime type next to the serialised form.

2023-07-13 20:27 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/resources/logback-ext-test.xml
> +    <logger name="org.terracotta.dynamic_config" level="TRACE"/>
ouch no!

2023-07-13 20:28 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/resources/logback-test.xml
> +  <logger name="org.terracotta.dynamic_config" level="TRACE" additivity="false">
no! forgot them! debugging purposes...

2023-07-13 20:29 UTC, mathieucarbou commented on pom.xml
> +        <version>2.10.1</version>
So I would say no, because this is 1 lib only and like all other lib, when only 1 lib, we don't have a property.

2023-07-13 20:44 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/Adapters.java
> +        float n = Float.parseFloat(value);
Ok so what I said is half-true for the non decimal values and false for decimal values. So I will change this parser and grab also your suggestion below for the integers and longs.

```
import com.fasterxml.jackson.databind.ObjectMapper
ObjectMapper json = new ObjectMapper()
println json.readValue(json.writeValueAsString([n: Float.MAX_VALUE]), Map).n.class // Double
println json.readValue(json.writeValueAsString([n: Double.MAX_VALUE]), Map).n.class // Double
println json.readValue(json.writeValueAsString([n: 0.1f]), Map).n.class // Double
println json.readValue(json.writeValueAsString([n: 0.1d]), Map).n.class // Double
println json.readValue(json.writeValueAsString([n: Byte.MAX_VALUE]), Map).n.class // Integer
println json.readValue(json.writeValueAsString([n: Short.MAX_VALUE]), Map).n.class // Integer
println json.readValue(json.writeValueAsString([n: Integer.MAX_VALUE]), Map).n.class // Integer
println json.readValue(json.writeValueAsString([n: Long.MAX_VALUE]), Map).n.class // Long
println json.readValue(json.writeValueAsString([n: Long.MAX_VALUE]), Map).n.class // Long
```

2023-07-13 20:52 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/Adapters.java
> +        float n = Float.parseFloat(value);
Note:  we currently don't have use case were we serialise floats and have to deserialise to floats. I even think we don't even have any decimal numbers going through json currently, but only ints or longs.

I am changing the code to copy the Jackon behviour, but if we think we want to change this behaviour for floats, in order to use floats, this would be possible and won't break backward compatibility.

2023-07-13 21:05 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/Adapters.java
> +        float n = Float.parseFloat(value);
Also I am noticing that the plain value notation we use (at least in TMC) is wrong because 1.0 is serialized as 1 and then would be deserialized as an int. 1.0f or 1.0d should be serialized as 1.0.

2023-07-13 21:32 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/gson/Adapters.java
> +        float n = Float.parseFloat(value);
ok so I've pushed a better version, with also a change in `FloatingPointTypeAdapter`

2023-07-17 16:15 UTC, chrisdennis commented on common/json-support/src/main/java/org/terracotta/json/DefaultJsonFactory.java
> +  private static class DirectedGraph<T> {
I was struggling to understand this code in the context of a directed graph, or its usage. I tried to rewrite things in this area just to test my understanding and ended up with the following:
```java
private static class DirectedGraph<T> {
  private final Map<T, Collection<T>> children = new LinkedHashMap<>();

  public void addEdge(T from, T to) {
    children.computeIfAbsent(from, k -> new LinkedHashSet<>()).add(to);
  }

  public Stream<T> depthFirstTraversal(final T root) {
    return depthFirstTraversal(root, new HashSet<>(children.size()));
  }

  private Stream<T> depthFirstTraversal(final T current, final Set<T> visited) {
    if (visited.add(current)) {
      return Stream.concat(children.getOrDefault(current, emptyList()).stream().flatMap(child -> depthFirstTraversal(child, visited)), Stream.of(current));
    } else {
      return empty();
    }
  }

  @Override
  public String toString() {
    return " - " + children.entrySet().stream().map(Object::toString).collect(joining(lineSeparator() + " - "));
  }
}
```
and then driving it:
```java
final DirectedGraph<Class<? extends Module>> graph = new DirectedGraph<>();
resolvedModules.keySet().forEach(type -> {
  graph.addEdge(RootModule.class, type);
  // we only override if the module to override has to be loaded.
  getOverrides(type).filter(resolvedModules::containsKey).forEach(overridden -> graph.addEdge(type, overridden));
  getDependencies(type).forEach(dependency -> graph.addEdge(type, dependency));
});

LOGGER.trace("Graph:{}{}", lineSeparator(), graph);

return graph.depthFirstTraversal(RootModule.class).map(resolvedModules::get).collect(toList());
```
This behaves the same as the original code with one small change. In the test where `C` overrides `A` we end up configuring `C` after `A` instead of before. This seems more logical to me... but I don't know enough about Gson to know if it's correct:
```java
@Test
public void test_override() {
  CALLS.clear();
  new DefaultJsonFactory().withModule(new B()).withModule(new C()).create();
  assertThat(CALLS, is(equalTo(asList("A", "B", "C"))));
}
```

2023-07-17 17:42 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/DefaultJsonFactory.java
> +  private static class DirectedGraph<T> {
@chrisdennis : this is the code I wrote first (depth first traversal) but it did work because the resulting list is not correctly sorted. The sorting algorithm is a little bit different.

It is possible to compare the output of traces when you put slf4j simple in trace mode.

@Dependency is just to declare modules that are required. So logically registered before but this is not required.

**@Override** is to make sure a module gets **configured before** another one.

This is linked to the documentation I've put in GsonFactory class. Gson has an internal list of factories, and when searching for a type adapter, it takes the first one it finds (there is one exception though when searching for the next factory, skipping the first one found).

So the logic is that in Gson, things having a higher priority should come first.

So that is why the sorting makes sure that overriding modules are configured first (in this case `C`) and then other ones.

2023-07-17 19:20 UTC, chrisdennis commented on common/json-support/src/main/java/org/terracotta/json/DefaultJsonFactory.java
> +  private static class DirectedGraph<T> {
If we just reverse the edge between `overridden` and `type` won't that get us where we want to be then?

2023-07-17 19:35 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/DefaultJsonFactory.java
> +  private static class DirectedGraph<T> {
@chrisdennis I ran a test and I cannot reproduce what I saw with your code. I might have made a mistake in my DFT code, or, I might have put the edges in the wrong order.

See:

```java
public class Main {
  public static void main(String[] args) {
    // A->B means:
    // - A is a dependency of B
    // - or A overrides B

    // A->B->C
    // A->D->C
    // D->E
    // F->A

    {
      final DefaultJsonFactory.DirectedGraph<String> graph = new DefaultJsonFactory.DirectedGraph<>();
      Stream.of("A", "B", "C", "D", "E", "F", "G").forEach(v -> {
        graph.addVertex(v);
        graph.addEdge("R", v);
      });

      graph.addEdge("A", "B");
      graph.addEdge("A", "D");
      graph.addEdge("B", "C");
      graph.addEdge("D", "C");
      graph.addEdge("D", "E");
      graph.addEdge("F", "A");

      System.out.println("SORT: " + graph.sort("R"));
      // [R, G, F, A, D, E, B, C] => OK
    }

    {
      final DefaultJsonFactory.DirectedGraph<String> graph = new DefaultJsonFactory.DirectedGraph<>();
      Stream.of("A", "B", "C", "D", "E", "F", "G").forEach(v -> {
        graph.addVertex(v);
        graph.addEdge("R", v);
      });

      graph.addEdge("A", "B");
      graph.addEdge("A", "D");
      graph.addEdge("B", "C");
      graph.addEdge("D", "C");
      graph.addEdge("D", "E");
      graph.addEdge("F", "A");

      final List<String> list = graph.depthFirstTraversal("R").collect(toList());
      Collections.reverse(list);
      System.out.println("DFT: " + list);
      // [R, G, F, A, D, E, B, C] => OK
    }
  }
}
```

I will update the code with yours and run the tests again... Your implementation is cleaner ;-)

2023-07-17 20:09 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/DefaultJsonFactory.java
> +  private static class DirectedGraph<T> {
Pushed a few changes :-)

2023-07-17 20:21 UTC, chrisdennis approved these changes

2023-07-17 20:21 UTC, chrisdennis commented on common/json-support/src/main/java/org/terracotta/json/util/DirectedGraph.java
> +  private final Map<T, Collection<T>> vertexEdges = new LinkedHashMap<>();
I think this can be a regular `HashMap`

2023-07-17 20:29 UTC, mathieucarbou commented on common/json-support/src/main/java/org/terracotta/json/util/DirectedGraph.java
> +  private final Map<T, Collection<T>> vertexEdges = new LinkedHashMap<>();
I wanted to preserve user ordering when a user declares 2 dependencies on a module

2023-07-18 17:22 UTC, merged