(draft) Switch from Maven to Gradle
Terracotta-OSS/terracotta-platform pull request #1194
Opened 2024-10-02 12:32 UTC by mathieucarbou

2024-12-19 14:57 UTC, mathieucarbou commented on resources/data-root/src/main/java/org/terracotta/config/data_roots/DataRootsDynamicConfigExtension.java
> +
Such check allow to have common layout between EE and OSS but only apply resources (or eventually services) when a license service is there

2024-12-20 15:46 UTC, mathieucarbou commented
@chrisdennis : gradle migration is finished, build pass locally. For now, the build runs through GitHub workflow (see link in my fork above), because I have a control over that).

We could decide to do a mix between building with GithHub or Azure and then deploying with Azure.

The only part remaining is then the CI part with Azure if we keep it, I just don't know which project to take as example.

Or should we for example do something like that: https://github.com/Terracotta-OSS/terracotta-utilities/blob/master/build.gradle.kts#L28-L57

2025-01-13 21:36 UTC, chrisdennis requested changes

2025-01-13 21:36 UTC, chrisdennis commented on dynamic-config/model/build.gradle
> +copyrightMainHeader {
This is better off done as:
```groovy
sourceSets {
  main {
    copyright {
      exclude '**/dict/*.txt 
    }
  }
}
```

2025-01-13 21:36 UTC, chrisdennis commented on dynamic-config/testing/integration-tests/build.gradle
> +copyrightTestUpdate {
Similar can be done through the copyright block.

2025-01-13 21:36 UTC, chrisdennis commented on kit/build.gradle.kts
> +        from (platformKit.map { fileTree(it.singleFile) }) {
Somehow this construction is losing the dependency on the configuration. Hence the need to add the dependencies in the tasks that consume the distribution contents. Something that might be worth looking at to simplify things.

2025-01-14 09:51 UTC, mathieucarbou commented on azure-pipelines.yml
> +      options: "--no-daemon"
please do not review the azure pipeline: I will rename the file to disabled. it does not support git submodule and matrix. Talked to @akomakom, we'll switch to github workflow, which works fine and is implemented in this PR, like terracotta-utilities. At least, until he has the time to fix the azure scripts.

2025-01-14 09:53 UTC, mathieucarbou commented on build-logic/src/main/java/org/terracotta/build/conventions/BaseConvention.java
> +  public static String toSagVersion(StructuredVersion v) {
I have switch to that, but don't have the knowledge to know if we can do more:
```java
      shadow.getExtensions().configure(OsgiManifestJarExtension.class, manifest -> {
        String version = ((StructuredVersion) project.getVersion()).toString();
        manifest.instruction(Constants.BUNDLE_VERSION, new MavenVersion(version).getOSGiVersion().toString());
      });
```

2025-01-14 09:55 UTC, mathieucarbou commented on build-logic/src/main/java/org/terracotta/build/plugins/ToolPlugin.java
> +public class ToolPlugin implements Plugin<Project> {
Created issue https://github.com/Terracotta-OSS/terracotta-platform/issues/1197 to do that after it is merged

2025-01-14 10:06 UTC, mathieucarbou commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/Tracker.java
Yes! And fyi, there is an ugliness in vscode, its that one of the java extension or plugin (don't remember because I've tried several combinations) is automatically reformatting the file on save. Here a spotbugs warning was fixed and saving the file made vscode reformat the javadoc I think. There are a couple like that, and I've discovered it laster in the process.

2025-01-14 10:06 UTC, mathieucarbou commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/OOOMessageHandler.java
Yes! And fyi, there is an ugliness in vscode, its that one of the java extension or plugin (don't remember because I've tried several combinations) is automatically reformatting the file on save. Here a spotbugs warning was fixed and saving the file made vscode reformat the javadoc I think. There are a couple like that, and I've discovered it laster in the process.

2025-01-14 10:13 UTC, mathieucarbou commented on common/json/src/test/java/org/terracotta/json/ClassTest.java
> + * Copyright Super iPaaS Integration LLC, an IBM Company 2025
Good catch! I've "fixup" some commits, leaving the gson changes alone, but this is wrong, I need to integrate the gson commit into the maven => gradle switch because the java 17 upgrade is handled inside.

2025-01-14 10:17 UTC, mathieucarbou commented on common/sanskrit/src/test/java/org/terracotta/persistence/sanskrit/SanskritIT.java
Same explanation as before will rollback.

2025-01-14 10:25 UTC, mathieucarbou commented on common/test-utilities/src/test/java/org/terracotta/testing/JavaToolTest.java
Same explanation as before will rollback.

2025-01-14 10:28 UTC, mathieucarbou commented on config/owasp-suppressions.xml
> +<suppressions xmlns="https://jeremylong.github.io/DependencyCheck/dependency-suppression.1.3.xsd">
oh thanks! I paid attention to checkstyle but did not notice this file!

2025-01-14 10:35 UTC, mathieucarbou commented on diagnostic/server/services/src/main/java/org/terracotta/diagnostic/server/extensions/DiagnosticExtensionsServiceProvider.java
> +
its a fix: I happened to see that when the KitInformation feature was added to the `DiagnosticExtensions`, it was not collected in the state dump. It should have been, since every server services are dumping their state into the server dump.

2025-01-14 10:39 UTC, mathieucarbou commented on dynamic-config/model/build.gradle
> +copyrightMainHeader {
what is the difference ?

2025-01-14 10:46 UTC, mathieucarbou commented on kit/build.gradle.kts
> +        from (platformKit.map { fileTree(it.singleFile) }) {
yes, here maybe I do not need since this is the same project (the test kit is build from the platform layout) ?

but I saw that on EE or Ehcahce, it won't be as simple....

that's why I was asking in the chat if we can do the way around, like declaring somewhere only the plugins / api that need to go in the kit and have a task that is taking that and builds the kit. Task could be reused, and the plugin / api descriptor could be extended in test kit / ehcache / ee.

2025-01-14 10:58 UTC, mathieucarbou commented on dynamic-config/testing/integration-tests/build.gradle
> +copyrightTestUpdate {
there were 2 occurrences to fix.

2025-01-14 10:59 UTC, mathieucarbou commented
@chrisdennis : PR updated, CI here until we can merge and switch to GitHub workflow: https://github.com/mathieucarbou/terracotta-platform/actions

2025-01-14 14:05 UTC, chrisdennis commented on build-logic/src/main/java/org/terracotta/build/conventions/BaseConvention.java
> +  public static String toSagVersion(StructuredVersion v) {
This bring up two questions:
1. Do you need things to be OSGi bundles.
2. If you do, is there any reason the bundle versions need to use "webMethods" version formatting?

2025-01-14 14:08 UTC, chrisdennis commented on dynamic-config/model/build.gradle
> +copyrightMainHeader {
exclude in the copyright block will exclude from both `copyrightMainUpdate` and `copyrightMainHeader` - and would better tolerate any changes in the `CopyrightPlugin` later on.

2025-01-14 14:41 UTC, mathieucarbou commented on build-logic/src/main/java/org/terracotta/build/plugins/ToolPlugin.java
> +public class ToolPlugin implements Plugin<Project> {
Created PR: https://github.com/Terracotta-OSS/terracotta-gradle-plugins/pull/33

2025-01-14 14:46 UTC, mathieucarbou commented on build-logic/src/main/java/org/terracotta/build/conventions/BaseConvention.java
> +  public static String toSagVersion(StructuredVersion v) {
I, myself, no 🤣 

Others ? Maybe... I don't know the complete users, what I do know is that this project publish libraries which will be dependencies of some public api in other projects, so ending up on client's classpath. So WebMethods is one of them I guess.

Now, do they need to be versioned like that or not, I don't know.

But looking deeper, this thing is part of the `ShadowJar` task and this project is not using any shadowing.

So the whole `project.getTasks().withType(ShadowJar.class)....` section could be removed!

2025-01-14 14:49 UTC, mathieucarbou commented on build-logic/src/main/java/org/terracotta/build/conventions/BaseConvention.java
> +  public static String toSagVersion(StructuredVersion v) {
I've pushed the removal.

2025-01-17 16:42 UTC, chrisdennis approved these changes

2025-01-17 17:00 UTC, merged