Genrating Friendly Node Names
Terracotta-OSS/terracotta-platform pull request #847
Opened 2020-08-19 10:39 UTC by mobasherul

2020-08-19 12:00 UTC, mathieucarbou commented on dynamic-config/model/src/main/resources/dictionaries/sports.txt
> +BaseBall
this list has too few items IMO... dangerous...

2020-08-19 12:02 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      count = 0;
The counter is going back to zero, no counter suffix is added, so this code only supports 5 stripes before failing since the stripe names will repeat.
Should we add another counter that will always be incremented and appended to the generated stripe name ?

2020-08-19 12:03 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +    builder.append("-stripe");
@jhouserizer : appending this suffix is inconsistent with the new config format. The suer will then have to use: `config-tool set -c stripe:Sport-stripe ...`  ? What a redundancy here ;-)
I suggest we remove any suffix when generating names.

2020-08-19 12:31 UTC, saurabhagas requested changes

2020-08-19 12:31 UTC, saurabhagas commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      int ind = ThreadLocalRandom.current().nextInt(0, allLines.size());
This has no guarantee that same name won't be chosen twice

2020-08-19 12:31 UTC, saurabhagas commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      List<String> allLines = readFromInputStream(inputStream);
Seems overkill to read all the dictionaries every time this method is method.

2020-08-19 12:31 UTC, saurabhagas commented on dynamic-config/model/src/main/resources/dictionaries/space.txt
> +Pandia
Other constellations could be added too.

2020-08-19 12:31 UTC, saurabhagas commented on dynamic-config/model/src/main/resources/dictionaries/animals.txt
> +Fancy rat varieties
I'd vote for one-word names everywhere. This is unnecessarily complex. If we need more animal names, there will be more out there. Zoology has advanced significantly :-D

2020-08-19 12:34 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      int ind = ThreadLocalRandom.current().nextInt(0, allLines.size());
That is OK. We just do not need that it gets chosen twice when names are generated. This only happens:
- when CLI si parsed for stripe name and node name
- when config is parsed for stripe name
- when xml is migrated for stripe name and node name
these are the only use cases

2020-08-19 12:35 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      List<String> allLines = readFromInputStream(inputStream);
this is acceptable IMO considering the very few times it is called (https://github.com/Terracotta-OSS/terracotta-platform/pull/847#discussion_r472993689)

2020-08-19 13:07 UTC, mobasherul commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      List<String> allLines = readFromInputStream(inputStream);
It won't read all the dictionaries . It will read only one of the file from dictionaries

2020-08-19 13:42 UTC, jhouserizer commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      count = 0;
I talked with Haque. There was a misunderstanding about where stripe names and node come from, so this will be resolved by some changes he's planning.  (i.e. "space" and "continent" are not to be stripe names, the longer list of things within them are stripe names).

2020-08-19 13:43 UTC, jhouserizer commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      count = 0;
again, this should be moot, with the changes Haque has now planned.

2020-08-19 13:43 UTC, jhouserizer commented on dynamic-config/model/src/main/resources/dictionaries/sports.txt
> +BaseBall
again, not relevant issue with the changes planned.

2020-08-19 13:44 UTC, jhouserizer commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +    builder.append("-stripe");
I have mixed feelings on this, but mostly disagree.   In the command line you showed, the word "stripe" is certainly redundant.  But elsewhere, in the properties file, in TMC screens, etc., the "-stripe" will add clarity.

2020-08-19 13:56 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +    builder.append("-stripe");
yes, that's right!

2020-08-20 08:13 UTC, saurabhagas commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/NameGenerator.java
> +      List<String> allLines = readFromInputStream(inputStream);
Ah right. But we'd need to handle the cases when we run out of names to give.

Also, does it give any value to store these names in files? If we're going to expose these files to users for them to add their own dictionaries, then it's a different story.

2020-08-25 02:37 UTC, merged