[WIP] Long Options POC
Terracotta-OSS/terracotta-platform pull request #879
Opened 2020-09-14 12:19 UTC by mobasherul

2020-09-14 12:20 UTC, mobasherul commented
mdh@eur.ad.sag@SAG-2H78NQ2-U:~/Myrepos/opensource/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.8-SNAPSHOT/platform-kit-5.8-SNAPSHOT/tools/bin$ ./config-tool.sh import-deprecated
Import a cluster configuration
Usage:
    import-deprecated -f <config-file> [-s <hostname[:port]>]
Options:
    -h, --help, -help
        Help
    -f (required)
        Config file
    -s
        Node to connect to

Error: The following option is required: [-f]
mdh@eur.ad.sag@SAG-2H78NQ2-U:~/Myrepos/opensource/terracotta-platform/dynamic-config/testing/system-tests/target/angela/kits/5.8-SNAPSHOT/platform-kit-5.8-SNAPSHOT/tools/bin$ ./config-tool.sh import
Import a cluster configuration
Usage:
    import -config-file <config-file> [-connect-to <hostname[:port]>]
Options:
    -h, --help, -help
        Help
    -config-file (required)
        Config file
    -connect-to
        Node to connect to

Error: The following option is required: [-config-file]

2020-09-14 21:29 UTC, mathieucarbou commented
@mobasherul : I don't understand... The long option "design" was already settled by discussions with @jhouserizer @saurabhagas me and other people. All the things to do are already partly done in #759.

I was out 1 week so I probably do not have enough context if something has changed...

If nothing has changed, why this new PoC ? This changes the UX a lot and would require to discuss it with @jhouserizer again. Except if this was done already ?

2020-09-15 11:57 UTC, mobasherul commented
> @mobasherul : I don't understand... The long option "design" was already settled by discussions with @jhouserizer @saurabhagas me and other people. All the things to do are already partly done in #759.
> 
> I was out 1 week so I probably do not have enough context if something has changed...
> 
> If nothing has changed, why this new PoC ? This changes the UX a lot and would require to discuss it with @jhouserizer again. Except if this was done already ?

2020-09-15 12:02 UTC, mobasherul commented
I have reverted my UI changes. Following is the list of output for different flavor of commands- 
1. ./config-tool.sh import --help
Import a cluster configuration
Usage:
    import -f <config-file> [-s <hostname[:port]>]
Options:
    -h, --help, -help
        Help
    -f (required)
        Config file
    -s
        Node to connect to

2../config-tool.sh import -help
Import a cluster configuration
Usage:
    import -config-file <config-file> [-connect-to <hostname[:port]>]
Options:
    -h, --help, -help
        Help
    -config-file (required)
        Config file
    -connect-to
        Node to connect to

3. ./config-tool.sh import -f ~/cf-single-stripe.properties 
Importing cluster configuration from config file: /home/mdh@eur.ad.sag/cf-single-stripe.properties to nodes: node-1-1@localhost:9410
Command successful!


4../config-tool.sh import -config-file ~/cf-single-stripe.properties 
Importing cluster configuration from config file: /home/mdh@eur.ad.sag/cf-single-stripe.properties to nodes: node-1-1@localhost:9410
Command successful!

2020-09-15 12:40 UTC, mathieucarbou commented
@mobasherul : FYI this is what people have settled on: https://github.com/Terracotta-OSS/terracotta-platform/pull/759#pullrequestreview-443972497

2020-09-29 01:35 UTC, mathieucarbou requested changes
@mobasherul : good work on this PR 👍 Lot of work done !

- please reformat all the modified files: there are a lot of formatting issues
- please reorganize all imports
- please rebase on master 

@jhouserizer @tmesic99 @mobasherul : __IMPORTANT__

there is one problem we didn't think yet... What if one day we need to deprecate another command to replace it with something else ? Currently, we canot be cause we only have --help and --deprecated-help and there is no versioning.

So instead of having the old commands but in a deprecated package with a @DeprecatedUsage annotation, should we instead introduce a @DeprecatedVersion flag and have --help and --v1-help, --v2-help, etc ? 

This is more complex to do, but if we force the US right now to have only --help and --deprecated-help, it means that if we need one day to deprecate another command t o change its UX, we will have no choice but to break compatibility, either with the current commands, or, remove the already deprecated ones and move the current to the deprecated ones.

WDYT ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/parsing/ConvertJCommanderCommand.java
> +  }
I don't really like that because we have a lot of implementations with duplicated code returning true, and these implementation all have `@DeprecatedUsage` already.

Instead of doing a check to `command.isDeprecated()`, why not just do: `command.getClass().isAnnotationPresent(DeprecatedUsage.class)` ? 

Deprecated commands can be detected with the `@DeprecatedUsage` annotation

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedConfigurationJCommanderCommand.java
> +public abstract class DeprecatedConfigurationJCommanderCommand extends JCommanderCommand {
I would remove this class and copy these fields capturing user input in the sub classes... I think this adds more complexity in having this super class that duplicating these fields where the user input is captured.

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedTopologyJCommanderCommand.java
> +public abstract class DeprecatedTopologyJCommanderCommand extends JCommanderCommand {
I would remove this class and copy these fields capturing user input in the sub classes... I think this adds more complexity in having this super class that duplicating these fields where the user input is captured.

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedDiagnosticJCommanderCommand.java
> +    requireNonNull(node);
we could remove this null checks: they are done by jcommander already

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedGetJCommanderCommand.java
> +    requireNonNull(configurations);
we could remove this null checks: they are done by jcommander already

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedRepairJCommanderCommand.java
> +    requireNonNull(node);
we could remove this null checks: they are done by jcommander already

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedSetJCommanderCommand.java
> +    requireNonNull(configurations);
we could remove this null checks: they are done by jcommander already

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedUnsetJCommanderCommand.java
> +    requireNonNull(configurations);
we could remove this null checks: they are done by jcommander already

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ActivateJCommanderCommand.java
> +@Usage("activate (-connect-to <hostname[:port]> | -config-file <config-file>) [-cluster-name <cluster-name>] [-restrict] [-license-file <license-file>] [-restart-wait-time <restart-wait-time>] [-rest
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/AttachJCommanderCommand.java
> +@Usage("attach (-to-cluster <hostname[:port]> -stripe <hostname[:port]> | -to-stripe <hostname[:port]> -node <hostname[:port]>) [-force] [-restart-wait-time <restart-wait-time>] [-restart-delay <rest
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ConfigurationJCommanderCommand.java
> +public abstract class ConfigurationJCommanderCommand extends JCommanderCommand {
I wouldn't bother with this class having only 2 fields... just copy them where needed ;-)

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/DetachJCommanderCommand.java
> +@Usage("detach(-from-cluster <hostname[:port]> -stripe [<hostname[:port]>|uid|name] | -from-stripe <hostname[:port]> -node [<hostname[:port]>|uid|name]) [-force] [-stop-wait-time <stop-wait-time>] [-
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/AttachJCommanderCommand.java
> +  @Parameter(names = {"-node"}, description = "Node to be Attached", converter = InetSocketAddressConverter.class)
Attach / Attached with uppercase A at several places...

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/DetachJCommanderCommand.java
> +  @Parameter(names = {"-node"}, description = "Node to be Detached", converter = IdentifierConverter.class)
Detach / Detached with uppercaseU at several places

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/DiagnosticJCommanderCommand.java
> +@Usage("diagnostic -connect-to <hostname[:port]>")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ExportJCommanderCommand.java
> +@Usage("export -connect-to <hostname[:port]> [-output-file <config-file>] [-include-defaults] [-runtime]")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/GetJCommanderCommand.java
> +@Usage("get -connect-to <hostname[:port]> [-runtime] -setting <[namespace:]setting>,<[namespace:]setting>...")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ImportJCommanderCommand.java
> +@Usage("import -config-file <config-file> [-connect-to <hostname[:port]>]")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/LockConfigJCommanderCommand.java
> +@Usage("lock-config -connect-to <hostname[:port]> -lock-context <context>")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/LogJCommanderCommand.java
> +@Usage("log -connect-to <hostname[:port]>")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/RepairJCommanderCommand.java
> +@Usage("repair -connect-to <hostname[:port]> [-force commit|rollback|reset|unlock]")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/SetJCommanderCommand.java
> +@Usage("set -connect-to <hostname[:port]> -setting <[namespace:]property=value>,<[namespace:]property=value>...")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/UnlockConfigJCommanderCommand.java
> +@Usage("unlock-config -connect-to <hostname[:port]>")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/UnsetJCommanderCommand.java
> +@Usage("unset -connect-to <hostname[:port]> -setting <[namespace:]property>,<[namespace:]property>...")
@jhouserizer @tmesic99 : if you can review before this is merged ?

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/ConfigTool.java
>      return jCommander;
can be inlined

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/JCommanderCommand.java
> +  public Command toCommand() {
I would rename it to `command()` or `getCommand()` and put it abstract instead of returning null. `toCommand()` implies a transformation to another type whereas `getCommand()` implied retuning an instance field, which is what is done here

2020-09-29 01:35 UTC, mathieucarbou commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/JCommanderCommandRepository.java
> +//  }
why commented ? original code was not. Is it unused now ? even in EE ?

2020-09-30 05:59 UTC, mobasherul commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/JCommanderCommandRepository.java
> +//  }
It is not required now we will inject at the time when command gets executed

2020-09-30 08:31 UTC, mobasherul commented
> @mobasherul : good work on this PR  Lot of work done !
> 
> * please reformat all the modified files: there are a lot of formatting issues
> * please reorganize all imports
> * please rebase on master
> 
> @jhouserizer @tmesic99 @mobasherul : **IMPORTANT**
> 
> there is one problem we didn't think yet... What if one day we need to deprecate another command to replace it with something else ? Currently, we canot be cause we only have --help and --deprecated-help and there is no versioning.
> 
> So instead of having the old commands but in a deprecated package with a @DeprecatedUsage annotation, should we instead introduce a @DeprecatedVersion flag and have --help and --v1-help, --v2-help, etc ?
> 
> This is more complex to do, but if we force the US right now to have only --help and --deprecated-help, it means that if we need one day to deprecate another command t o change its UX, we will have no choice but to break compatibility, either with the current commands, or, remove the already deprecated ones and move the current to the deprecated ones.
> 
> WDYT ?

FYI - I haven't added --deprecated-help support for both config-tool commands and server startup options. For server startup help option is controlled from core.Currently only help option is displayed. How it is working currently is I am registering commands as <command-deprecated> and that's how it is working with deprecated options.

2020-09-30 15:14 UTC, mathieucarbou requested changes
- LOT of things unresolved from my last review (expand the list - marked them as _ unresolved_)
- Still some files requiring import reorg or reformatting
![image](https://user-images.githubusercontent.com/61346/94704642-216ab980-030e-11eb-8b67-508b0896496c.png)

2020-09-30 15:14 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/ConfigTool.java
>      return jCommander;
can be inlined

2020-09-30 15:15 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +import org.terracotta.dynamic_config.server.configuration.startup.deprecated_parsing.DeprecatedOptionsParsingImpl;
unresolved

2020-09-30 15:16 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/parsing/ConvertJCommanderCommand.java
> +  }
unresolved

2020-09-30 15:17 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedConfigurationJCommanderCommand.java
> +public abstract class DeprecatedConfigurationJCommanderCommand extends JCommanderCommand {
unresolved

2020-09-30 15:17 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedTopologyJCommanderCommand.java
> +public abstract class DeprecatedTopologyJCommanderCommand extends JCommanderCommand {
unresolved

2020-09-30 15:18 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedRepairJCommanderCommand.java
> +    requireNonNull(node);
unresolved

2020-09-30 15:18 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedDiagnosticJCommanderCommand.java
> +    requireNonNull(node);
unresolved

2020-09-30 15:18 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedGetJCommanderCommand.java
> +    requireNonNull(configurations);
unresolved

2020-09-30 15:18 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedSetJCommanderCommand.java
> +    requireNonNull(configurations);
unresolved

2020-09-30 15:18 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/deprecated_parsing/DeprecatedUnsetJCommanderCommand.java
> +    requireNonNull(configurations);
unresolved

2020-09-30 15:19 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/AttachJCommanderCommand.java
> +  @Parameter(names = {"-node"}, description = "Node to be Attached", converter = InetSocketAddressConverter.class)
unresolved

2020-09-30 15:19 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/DetachJCommanderCommand.java
> +  @Parameter(names = {"-node"}, description = "Node to be Detached", converter = IdentifierConverter.class)
unresolved

2020-09-30 15:20 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/ConfigTool.java
>      return jCommander;
unresolved

2020-09-30 17:56 UTC, mathieucarbou commented
there are still some files to reformat. Will do that in another PR

2020-09-30 17:56 UTC, mathieucarbou approved these changes

2020-09-30 19:15 UTC, merged