simplify message tracker implementation and interface
Terracotta-OSS/terracotta-platform pull request #884
Opened 2020-09-17 16:21 UTC by myronkscott

2020-09-17 16:24 UTC, myronkscott commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/ClientTrackerImpl.java
> -  public ClientTrackerImpl(Predicate<?> trackerPolicy) {
was redundant

2020-09-17 16:24 UTC, myronkscott commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/OOOMessageHandler.java
> +  R invoke(InvokeContext context, M message, Supplier<R> invoke) throws EntityUserException;
redundant.  since caller knows the parameters, the BiFunction is not needed.

2020-09-17 16:24 UTC, myronkscott commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/OOOMessageHandler.java
> +  void closeDuplicatesWindow();
not sure if this is desired.  minor speedup if any.

2020-09-21 20:31 UTC, chrisdennis requested changes

2020-09-21 20:31 UTC, chrisdennis commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/OOOMessageHandler.java
> +  R invoke(InvokeContext context, M message, Supplier<R> invoke) throws EntityUserException;
This means we're going to be forced to capture state in the lambda... which might mean it can't be a lambda (ever).

2020-09-21 20:31 UTC, chrisdennis commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/ClientTrackerImpl.java
>      for (Entry<ClientSourceId, TrackerImpl<M, R>> t : objectTrackers.entrySet()) {
This can changed to: 
```java
return objectTrackers.entrySet().stream().flatMap(t -> t.getValue().getTrackedValues().stream().map(e -> convert(t.getKey(), e)));
```

2020-09-21 20:31 UTC, chrisdennis commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/OOOMessageHandlerImpl.java
> +    return clientMessageTracker.getTrackedValues().sorted((r1,r2)->(int)(r1.getSequenceId() - r2.getSequenceId())).map(SequencedRecordedMessage::convert);
```
comparingLong(RecordedMessage::getSequenceId)
```

2020-09-21 20:31 UTC, chrisdennis commented on client-message-tracker/src/main/java/org/terracotta/client/message/tracker/OOOMessageHandlerImpl.java
> +  public R getTrackedResponse(ClientSourceId source, long id) {
This looks to be unused, is it fully replaced by `lookupResponse(...)`? If not could they have similar names that mark their similarities/differences better?

2020-09-23 18:11 UTC, chrisdennis approved these changes

2020-09-24 05:00 UTC, merged