synchronize runtime-modifiable server config attributes with server m…
Terracotta-OSS/terracotta-platform pull request #885
Opened 2020-09-17 23:22 UTC by GaryWKeim

…anagement model

2020-09-17 23:23 UTC, GaryWKeim commented
This is primarily for publicHostname and publicPort but bringing along all runtime modifiable DC attributes for future TMC features.

2020-09-18 00:13 UTC, GaryWKeim commented
Need to re-anchor this PR to an earlier commit.

2020-09-18 15:14 UTC, mathieucarbou commented on management/cluster-topology/src/main/java/org/terracotta/management/model/cluster/Server.java
> +    if (!Objects.equals(loggerOverrides, server.loggerOverrides)) return false;
if the build passes, I am glad. 
I prefer also not using `{ }` with simple lines like that but one day when I've tried I got a checkstyle complain... Don't remember thought if it was for OSS or EE.

2020-09-18 15:19 UTC, mathieucarbou commented on management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/TopologyService.java
> +    if (!extendedConfiguration.isEmpty()) {
No need: `DynamicConfigEventService ` will always be there (thing is wired at startup) and there will be only one

2020-09-18 18:42 UTC, GaryWKeim commented on management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/TopologyService.java
> +    if (!extendedConfiguration.isEmpty()) {
Problem is with Angela tests that don't setup the service provider fully.

2020-09-18 18:59 UTC, mathieucarbou commented on management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/TopologyService.java
> +    if (!extendedConfiguration.isEmpty()) {
> Problem is with Angela tests that don't setup the service provider fully.

weird... DC is managing the server startup and implements the `PlatformConfiguration` interface so this is DC tha tis providing the components. There is no way this service can be missing except if you start with an old 10.x, it is even available in diagnostic mode.

If you happen to see it again you'll have to show me because this might be a bug!

2020-09-26 12:47 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activation/ActivateCommand1x2IT.java
> +  // This test failed for me on 9/22/20... intermittent
what was the failure ? if it fails and you see in the server logs a bind port, this is not caused by the test or DC...

2020-09-26 13:09 UTC, mathieucarbou commented on management/cluster-topology/pom.xml
> +          <scope>compile</scope>
scope can be removed

2020-09-26 14:35 UTC, mathieucarbou requested changes

2020-09-26 14:35 UTC, mathieucarbou commented on management/monitoring-service/src/main/java/org/terracotta/management/service/monitoring/TopologyService.java
> +    server.setUID(node.getUID());
ok I see... UID cannot be final because you do not know it yet...

2020-09-28 17:50 UTC, GaryWKeim commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activation/ActivateCommand1x2IT.java
> +  // This test failed for me on 9/22/20... intermittent
One of the activate commands timed-out looking for the proper output.

2020-09-28 17:50 UTC, GaryWKeim commented on management/cluster-topology/pom.xml
> +      </dependency>
Yeah, this is what happens when you let IntelliJ add the dependency.

2020-09-28 17:51 UTC, GaryWKeim commented on management/cluster-topology/src/main/java/org/terracotta/management/model/cluster/Server.java
> +  private String metadataDir;
Which one? All of them?

2020-09-28 17:55 UTC, GaryWKeim commented on management/cluster-topology/src/main/java/org/terracotta/management/model/cluster/Server.java
> +  private String securityAuditLogDir;  // taken at runtime from servers
Will do.

2020-09-28 17:56 UTC, GaryWKeim commented on management/cluster-topology/src/test/java/org/terracotta/management/model/cluster/AbstractTest.java
> +    UID uid = UID.valueOf("VOVyu3kuQxCRIu7dK_UZZA");
But this UID needs to match those in a static JSON test resource file and the ones in Testing are all dynamically generated.

2020-09-29 18:30 UTC, mathieucarbou commented on management/cluster-topology/src/main/java/org/terracotta/management/model/cluster/Server.java
> +  private String metadataDir;
`metadataDir ` ;-) this is the special case. either always there, either always null

2020-09-29 18:31 UTC, mathieucarbou commented on management/cluster-topology/src/test/java/org/terracotta/management/model/cluster/AbstractTest.java
> +    UID uid = UID.valueOf("VOVyu3kuQxCRIu7dK_UZZA");
They are always generated, yes, but since I am using a fixed seed to generate them, they will always have the same values ;-) That's the trick :P

2020-10-01 21:03 UTC, mathieucarbou approved these changes

2021-04-19 23:13 UTC, closed without merging