Refactoring for jcommander parsing.
Terracotta-OSS/terracotta-platform pull request #916
Opened 2020-11-16 08:55 UTC by mobasherul

2020-11-16 22:51 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/pom.xml
> +      <artifactId>dynamic-config-cli-config-tool-api</artifactId>
I find the name a bit long: WDYT about `dynamic-config-cli-api` ? Because this module could hold api classes used in other CLI, like migration. why not...

2020-11-16 22:52 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/ConfigTool.java
> +    Collection<Object> services = ServiceProvider.get().createServices((RemoteMainCommand)mainCommand.getCommand());
Why do we need the cast here ? Cant't `RemoteMainJCommanderCommand ` extend `RemoteMainCommand ` ?

2020-11-16 22:56 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/ConfigTool.java
> +    Collection<Object> services = ServiceProvider.get().createServices((RemoteMainCommand)mainCommand.getCommand());
Or return `RemoteMainCommand ` instead of `Command` in the `getCommand()` implementation ?

2020-11-16 22:58 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-config-tool-api/pom.xml
> +            <artifactId>dynamic-config-cli-support</artifactId>
We really need cli-support for the api ?
I am wondering if we could get rid of that ? 
I think cli-support depends on jcommander and has some jcommander stuff ?

2020-11-16 22:59 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-config-tool-api/pom.xml
> +            <artifactId>client-runtime</artifactId>
I wouldn't put that in an api module - we could depend on the connection apis here in provided scope

2020-11-16 23:00 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-config-tool-api/src/main/java/org/terracotta/dynamic_config/cli/config_tool/api/command/RemoteMainCommand.java
> +public class RemoteMainCommand extends LocalMainCommand {
We could now rename `LocalMainCommand ` to `LocalCommand ` and `RemoteMainCommand ` to `RemoteCommand ` because there is no concept of main jcommander command anymore here

2020-11-16 23:01 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/pom.xml
> +      <artifactId>dynamic-config-cli-config-tool</artifactId>
why this dependency has been added ? upgrade tool should not depend on config tool

2020-11-16 23:02 UTC, mathieucarbou commented on kit/pom.xml
> +      <artifactId>dynamic-config-cli-config-tool-api</artifactId>
you do not need to declare the dependency in the pom since it comes transitively.

2020-11-16 23:02 UTC, mathieucarbou commented on kit/src/main/assembly/platform-kit.xml
> +        <include>org.terracotta.dynamic-config.cli:dynamic-config-cli-config-tool</include>
why ?

2020-11-17 08:01 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-config-tool-api/pom.xml
> +            <artifactId>client-runtime</artifactId>
Its not only using connection apis but also ManagedServiceLoader.

2020-11-17 08:03 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-config-tool-api/pom.xml
> +            <artifactId>dynamic-config-cli-support</artifactId>
cli-support has CustomJCommander and LocalJCommanderCOmmand which is used for ConfigConvertorTool as well  thats how it is ensured that upgrade tools won't depend on anything related to config tool.

2020-11-17 08:29 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-config-tool-api/src/main/java/org/terracotta/dynamic_config/cli/config_tool/api/command/RemoteMainCommand.java
> +public class RemoteMainCommand extends LocalMainCommand {
There already exists file named RemoteCommand

2020-11-23 18:58 UTC, mathieucarbou requested changes
@mobasherul : there is 2 things left in the pom and it is good to go 👍 thanks!

2020-11-23 18:58 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/pom.xml
> +      <artifactId>dynamic-config-cli-config-tool</artifactId>
not resolved: upgrade tool should not depend on config tool

2020-11-23 18:58 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/pom.xml
> +      <artifactId>dynamic-config-cli-api</artifactId>
not needed: it will come through cli-support

2020-11-23 19:11 UTC, mobasherul commented on dynamic-config/cli/upgrade-tools/pom.xml
> +      <artifactId>dynamic-config-cli-config-tool</artifactId>
Missed to remove from pom. FIxed now.

2020-11-30 15:14 UTC, mathieucarbou approved these changes

2020-11-30 15:17 UTC, merged