Reduce coupling between JCommander commands and the actions they trigger
Terracotta-OSS/terracotta-platform pull request #919
Opened 2020-12-10 23:14 UTC by chrisdennis

2020-12-11 16:41 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/command/OssCommandProvider.java
> +    Set<Command> commands = new HashSet<>();
I was thinking yesterday about the extensibility of this thing and I do not really like that. Having a bag of items makes defining a different flavour harder because we would need to copy/paste all of this again, or manipulate the collection and try to find the right item to remove...

I am wondering if we should instead extract methods (like it is done in `OssServiceProvider`: 1 method for each service), or return a Map where the key would be the action for example ? or command ?

2020-12-11 16:58 UTC, mobasherul commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/command/OssCommandProvider.java
> +    Set<Command> commands = new HashSet<>();
Instead of functions for each command map would be better if we are taking this route.

2020-12-11 16:59 UTC, chrisdennis commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/command/OssCommandProvider.java
> +    Set<Command> commands = new HashSet<>();
I think the JCommander aligned approach here would be to make them a list?

2020-12-11 17:30 UTC, mathieucarbou requested changes
@chrisdennis also, I saw at least one unused import (in RemoteMainCommand I think).
You can do a global format / reorganize imports in theory in this project: all the team is suing the same settings so that should work.

2020-12-11 17:30 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LocalConfig.java
> +public class LocalConfig implements Runnable {
Could you take this opportunity to remove `implements Runnable` from `LocalConfig ` ?

LocalConfig and RemoteConfig are now just configuration classes passed to the service provider to create the services.

The problem is that they are also used to execute something (setup of the logging system). Which is wrong.

We could then introduce a `MainAction` that would be used in the `LocalMainCommand` and a `MainRemoteAction` that would be used in `RemoteMainCommand`, to match what is done elsewhere.

2020-12-11 17:30 UTC, mathieucarbou commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/LocalMainCommand.java
> +  private final LocalConfig config;
`private final MainAction action;` (see my other comment)

2020-12-11 17:30 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/ConfigTool.java
> +        Injector.inject(command, services);
👍

2020-12-11 17:30 UTC, mathieucarbou commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/LocalMainCommand.java
> +    getConfiguration().run();
related to my other comment... Or we could just remove the logging code from LocalConfig and just put it there...

2020-12-11 17:30 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/Injector.java
> +            if (targetValue == null) {
if we check for null, why annotating action fields with `@Inject` ? These fields will never be null so won't be injected ?

```
  @Inject
  public final ImportAction action;

  public ImportCommand() {
    this(new ImportAction());
  }
```

We are controlling the commands through service override, so why not just remove `@Inject` in then and make the fields private ?

2020-12-11 19:10 UTC, chrisdennis commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/LocalMainCommand.java
> +    getConfiguration().run();
Done

2020-12-11 19:10 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/Injector.java
> +            if (targetValue == null) {
Clarified.

2020-12-11 19:16 UTC, mathieucarbou requested changes

2020-12-11 19:16 UTC, mathieucarbou commented on dynamic-config/cli/cli-support/src/main/java/org/terracotta/dynamic_config/cli/command/LocalMainCommand.java
> +  public LocalMainCommand() {
can be removed

2020-12-14 14:34 UTC, mathieucarbou approved these changes

2020-12-15 15:06 UTC, mathieucarbou approved these changes

2020-12-15 15:06 UTC, merged