Introducing command output service.
Terracotta-OSS/terracotta-platform pull request #921
Opened 2020-12-28 15:16 UTC by mobasherul

2020-12-28 15:17 UTC, mobasherul commented
Introducing command output service so that user can pipe command output for their needs. Rest of the logging is now redirected to stderr.

2021-01-05 19:19 UTC, mathieucarbou requested changes

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    consoleOutputService.write("Command successful!");
- I would rename this variable to just "out" or "console"

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ActivateCommand.java
> +@Usage("(-connect-to <hostname[:port]> | -config-file <config-file>) [-cluster-name <cluster-name>] [-restrict] [-license-file <license-file>] [-restart-wait-time <restart-wait-time>] [-restart-delay
can you extract this fix to another PR that we will merge right away ?

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/ConsoleOutputService.java
> +  public void write(String msg) {
I would call it `println`

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/ConsoleOutputService.java
> +  public void write(String format, Object... args) {
I would call it `println`

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/command/ConvertAction.java
> +
I am not sure we need that: we could use @Inject.

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/parsing/ConvertCommand.java
> +    action.setConsoleOutputService(new ConsoleOutputService());
no need: @Inject should work

2021-01-05 19:19 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/parsing/deprecated/DeprecatedConvertCommand.java
> +    action.setConsoleOutputService(new ConsoleOutputService());
no need: @Inject should work

2021-01-05 20:27 UTC, chrisdennis requested changes
Lots of decisions to be made on syserr vs sysout here. This happens naturally when we start to think about what the 'output' of each of these commands is (for some it's probably nothing).

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/ConsoleOutputService.java
> +public class ConsoleOutputService {
Why is this a concrete class and not say `java.lang.Appendable` or something equivalently abstract.

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    consoleOutputService.write("Command successful!");
I would vote for output. Output is what it is, console is just where it might get sent to.

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/AttachAction.java
> +        consoleOutputService.write("Attaching node: {} to stripe: {}", source, cluster.getStripeByNode(destination.getNodeUID()).get().toShapeString());
It's not clear to me that this output... should attach and other commands with no logical 'output' instead push all logging through syserr?

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +    consoleOutputService.write("Command successful!");
Seems like this should be syserr.

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +        consoleOutputService.write("Output saved to: {}" + lineSeparator(), outputFile);
Should this be syserr? Should we achieve file export by rerouting the `output` thing?

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ImportAction.java
> +    consoleOutputService.write("Importing cluster configuration from config file: {} to nodes: {}", configPropertiesFile, toString(runtimePeers));
Syserr?

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    consoleOutputService.write("Configuration logs from {}:", node);
Syserr?

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
> +    consoleOutputService.write("Activating nodes: " + toString(newNodes));
Syserr?

2021-01-05 20:27 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
> +        consoleOutputService.write("No license installed. If you are attaching a node, the license will be synced.");
Definitely syserr.

2021-01-05 20:40 UTC, mathieucarbou requested changes

2021-01-05 20:40 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +    consoleOutputService.write("Command successful!");
@mobasherul : I see you have moved the line after the `else`... It should be inside like before

2021-01-05 20:42 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
> +        consoleOutputService.write("No license installed. If you are attaching a node, the license will be synced.");
👍

2021-01-05 20:44 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
> +    consoleOutputService.write("Activating nodes: " + toString(newNodes));
No not this one: this is the description of what the command will do and on which nodes... I think this is OK to have it in the user output. This command does not output any specific data expect "steps" that it is going through.

stderr is reserved for verbose / debug usage, or errors. The user is not supposed to go there to look at what his command is doing right now...

2021-01-05 20:45 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/AttachAction.java
> +        consoleOutputService.write("Attaching node: {} to stripe: {}", source, cluster.getStripeByNode(destination.getNodeUID()).get().toShapeString());
No not this one: this is the description of what the command will do and on which nodes... I think this is OK to have it in the user output. This command does not output any specific data except "steps" that it is going through.

stderr is reserved for verbose / debug usage, or errors. The user is not supposed to go there to look at what his command is doing right now...

2021-01-05 20:48 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +        consoleOutputService.write("Output saved to: {}" + lineSeparator(), outputFile);
If we remove this line, yes we could decide to remove the option to export to a file:-) I am OK with that, makes sense.
PM @jhouserizer might tell ;-)

2021-01-05 20:48 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ImportAction.java
> +    consoleOutputService.write("Importing cluster configuration from config file: {} to nodes: {}", configPropertiesFile, toString(runtimePeers));
No not this one: this is the description of what the command will do and on which nodes... I think this is OK to have it in the user output. This command does not output any specific data except "steps" that it is going through.

stderr is reserved for verbose / debug usage, or errors. The user is not supposed to go there to look at what his command is doing right now...

2021-01-05 20:50 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    consoleOutputService.write("Configuration logs from {}:", node);
yes, or... simply just remove it... only logs should be outputted here

2021-01-06 06:05 UTC, mobasherul commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ActivateCommand.java
> +@Usage("(-connect-to <hostname[:port]> | -config-file <config-file>) [-cluster-name <cluster-name>] [-restrict] [-license-file <license-file>] [-restart-wait-time <restart-wait-time>] [-restart-delay
https://github.com/Terracotta-OSS/terracotta-platform/pull/922

2021-01-08 00:11 UTC, mathieucarbou requested changes

2021-01-08 00:11 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}{}", lineSeparator(), formattedChanges, lineSeparator());
we could remove the final `Command successful!` like you did at the other places

2021-01-08 00:11 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
> +    output.println("Unlocked the config.");
I would change that to: "Config unlocked."

2021-01-08 00:11 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/command/ConvertAction.java
> +
Extra space

2021-01-08 00:11 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/parsing/ConvertCommand.java
> +
extra spaces

2021-01-08 00:11 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/parsing/deprecated/DeprecatedConvertCommand.java
> +
extra spaces

2021-01-08 06:38 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}{}", lineSeparator(), formattedChanges, lineSeparator());
something like output.println("{}{}, lineSeparator(), formattedChanges) ?

2021-01-08 14:29 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}{}", lineSeparator(), formattedChanges, lineSeparator());
yes. I saw you have removed all "double" line separators we had (which I completely agree with). So let's be consistent everywhere.

2021-01-08 14:29 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}", lineSeparator(), formattedChanges);
👍

2021-01-08 14:31 UTC, mathieucarbou requested changes

2021-01-08 14:31 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
> +    output.println("Locked the config.");
Missed this one, sorry... It should be: "Config locked"

2021-01-08 15:05 UTC, mathieucarbou approved these changes

2021-01-08 15:19 UTC, chrisdennis requested changes
Still think there might be some misclassifications of out vs error.

2021-01-08 15:19 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
Is this needed? Isn't this synonymous with a '0' exit code?

2021-01-08 15:19 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/GetAction.java
> +      output.println(out);
Could this become a sequence of output calls rather than a string assemble?

2021-01-08 15:19 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}", lineSeparator(), formattedChanges);
Why a leading line separator?

2021-01-08 15:19 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +public interface OutputService {
Why do we need a new interface?

2021-01-08 15:24 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
I think its fine to display it.

2021-01-08 15:26 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}", lineSeparator(), formattedChanges);
If they don't redirect the stdout it will be more readable when somebody fires this command

2021-01-08 15:27 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +public interface OutputService {
I introduced this so if someone wants to have a some different implementation when we want to do something else to the output of command we can use some other implementation than directly printing on stdout.

2021-01-08 16:12 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/GetAction.java
> +      output.println(out);
And @mobasherul : same thing for the log command: the output of the content (not the header but the lines) could be streamed with "output.println" instead of built and sent at once.

2021-01-08 16:19 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
The reason Saurabh initially put it in most of the commands was to tell the user everything went fine because otherwise he only see some middle "steps"but no completion step saying "finished".
Also, for some tests, I remember we had to rely on that because we could not access the exist status.

Personally I do not have a string opinion on these things: whether:
1)  to remove ALL output for commands that are doing "actions" and only rely on exit codes
2)  to have middle step outputs hinting the user what the command is doing and when it is finished

Knowing that some commands might be slow, or run into some timeouts, I find 2) to be better suited though and provide better feedback.

2021-01-08 16:22 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +    output.println("{}{}", lineSeparator(), formattedChanges);
Personally, I am not a fan of all these empty lines in the output. I would prefer to not have empty lines at all, for all commands :-)

2021-01-11 14:37 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +      output.println("<empty>");
I would remove this "empty" placeholder and only print logs if there are some logs.
WDYT @chrisdennis ?

2021-01-11 14:38 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +      output.println("<empty>");
Agreed

2021-01-11 14:46 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +      output.println("<empty>");
ok I will remove then empty placeholder.

2021-01-11 14:55 UTC, mathieucarbou approved these changes

2021-01-11 15:09 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +public interface OutputService {
Right... but why does it need to be a new interface. Isn't there something suitable in the JDK already? (`java.lang.Appendable`?)

2021-01-11 15:13 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
I guess maybe I don't see a 'holistic' plan here. It's not clear which things belong on stdout, which on stderr, which should visible by default, etc. I generally prefer my CLIs on the quiet side by default unless something goes wrong.

2021-01-11 15:14 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +        consoleOutputService.write("Output saved to: {}" + lineSeparator(), outputFile);
I'm not saying to remove the option... i'm saying the option could be implemented using a redirect of the output service internally.

2021-01-11 15:18 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
Well, it depends": for commands that could take a long time, I personally like to have a status to ensure the command is not stalled.

2021-01-11 15:23 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
Right... but should that be sys-error or sys-out?

2021-01-12 07:00 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +public interface OutputService {
I am not going with Appendable because it's apis are too low level such as -
1.  public Appendable append(char c) ;
2.  public Appendable append(CharSequence csq, int start, int end);

2021-01-12 18:32 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +public interface OutputService {
If thats too low-level then what about taking a `java.io.Writer` in and then wrapping it as a `PrintWriter` for internal consumption. This gives more printey methods than you can shake a stick at. I just don't see this interface doing enough work to justify it's existence.

2021-01-14 04:51 UTC, mathieucarbou requested changes
- there is a LOGGER.info to change perhaps to trace in `DefaultNomadManager`...
- we could move to `trace` the `LOGGER.info` in ConfigRepoProcessor I think...

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +        LOGGER.warn(outputFile + " already exists. Replacing this file.");
This shouldn't be a warning since otherwise it will come with a timestamp, class name, etc. I think we should use output.info here (go to stderr).

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +        throw new RuntimeException(e);
why can't we have like before a global:
```
catch (IOException e) { } { throw new UncheckedIOException(e); }
```

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/LogAction.java
> +        .forEach(s -> output.out(s));
`output::out`

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/FileOutputService.java
> +    super(new PrintStream(path.toString(), StandardCharsets.UTF_8.name()), System.err);
no need for `.name()`

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/ConfigConverter.java
> +
extra line ?

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
>    private Optional<Cluster> loadTopologyFromConfig() {
- In `loadTopologyFromConfig()`: use output.info
- In `loadTopologyFromNode()`: use output.info

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/AttachAction.java
> +        output.info("Attaching node: {} to stripe: {}", source, cluster.getStripeByNode(destination.getNodeUID()).get().toShapeString());
there is a `LOGGER.warn()` also to replace above.

@chrisdennis : what do you propose for all `LOGGER.warn()` replacements ? Switching to `output.info()` too (which will go to stderr ? This is to avoid outputting some timestamps, class names, etc. We should not go to te LOGGER in "normal" mode.

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +      output.info("Applying new configuration change(s) to activated cluster: {}", toString(onlineNodes.keySet()));
2x `LOGGER.warn` to replace above

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/DetachAction.java
> +      output.info("Stopping nodes: {}", toString(onlineNodesToRemove));
Also 2x `LOGGER.warn` in this file

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ImportAction.java
> +    output.info("Importing cluster configuration from config file: {} to nodes: {}", configPropertiesFile, toString(runtimePeers));
We have a `LOGGER.warn` in this file

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
>        progress.getErrors().forEach((address, e) -> LOGGER.warn("Unable to ask node: {} to stop: please stop it manually.", address));
there is a LOGGER.warn in stopNodes() method to change

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RepairAction.java
> +    output.info("Command successful!");
there are 2x LOGGER.warn in this file

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/TopologyAction.java
> +    output.info("Command successful!");
a LOGGER.warn in this file to replace

2021-01-14 04:51 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/ConfigConverter.java
>  public class ConfigConverter {
LOGGER.warn in this file

2021-01-14 04:57 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ExportAction.java
> +        LOGGER.warn(outputFile + " already exists. Replacing this file.");
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:57 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/AttachAction.java
> +        output.info("Attaching node: {} to stripe: {}", source, cluster.getStripeByNode(destination.getNodeUID()).get().toShapeString());
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:57 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/DetachAction.java
> +      output.info("Stopping nodes: {}", toString(onlineNodesToRemove));
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:58 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +      output.info("Applying new configuration change(s) to activated cluster: {}", toString(onlineNodes.keySet()));
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:58 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RepairAction.java
> +    output.info("Command successful!");
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:58 UTC, mathieucarbou commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/ConfigConverter.java
>  public class ConfigConverter {
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:58 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/TopologyAction.java
> +    output.info("Command successful!");
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 04:58 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/RemoteAction.java
>        progress.getErrors().forEach((address, e) -> LOGGER.warn("Unable to ask node: {} to stop: please stop it manually.", address));
forget about that! default behaviour is not to have a pattern in the logging output so that's fine!

2021-01-14 15:45 UTC, chrisdennis reviewed
It's become clear to me that maybe I don't understand (or maybe never understood) the purpose behind these changes. Documenting the `OutputService` might help clarify what that abstraction is trying to achieve. In that light I think it's best to take my review comments as advisory only and to not wait for my approval.

These changes are definitely an improvement on what was there before. I'm not sure however that what I want this PR to achieve (and what my comments are trying to steer it in the direction of) are the same as what everyone else want it to achieve.

2021-01-14 15:45 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +  protected PrintStream outStream;
Why is this `protected` and not `private`?

2021-01-14 15:45 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +  protected PrintStream outStream;
Why isn't it final?

2021-01-14 15:45 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +  public void out(String format, Object... args) {
Why is one of the methods named for the "where things are going"? Why is the other named for a logging level?

2021-01-14 15:45 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +  public OutputService(PrintStream outStream, PrintStream errStream) {
These should really be a PrintWriter since we're dealing purely with characters (at this layer).

2021-01-14 15:45 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +public class OutputService {
Since the title of this PR is 'Introducing command output service' it seems a mistake that we're not javadocing the newly introduced class. That should make it clearer what the purpose of this class is.

2021-01-14 15:45 UTC, chrisdennis commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/FileOutputService.java
> +    super(new PrintStream(path.toString(), StandardCharsets.UTF_8.name()), System.err);
It makes my brain hurt to think about this... but it's not entirely clear that this always the right encoding to use.

2021-01-18 06:47 UTC, mobasherul commented on dynamic-config/cli/upgrade-tools/src/main/java/org/terracotta/dynamic_config/cli/upgrade_tools/config_converter/ConfigConverter.java
> +
extra line was there earlier I removed it.

2021-01-18 06:50 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/FileOutputService.java
> +    super(new PrintStream(path.toString(), StandardCharsets.UTF_8.name()), System.err);
It is required as the signature expects string.

2021-01-18 07:05 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +  public OutputService(PrintStream outStream, PrintStream errStream) {
Problem with PrintWriter is it will not print anything on the outputstream unless the PrintWriter is closed that's why I am going with PrintStream.

2021-01-18 07:07 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/OutputService.java
> +  public void out(String format, Object... args) {
out is something which is redirected to stdout which resembles actual command output.
info is redirected the steps of the command execution to stderr.Basically it gives information when command is in execution.

2021-01-18 08:23 UTC, mobasherul commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/FileOutputService.java
> +    super(new PrintStream(path.toString(), StandardCharsets.UTF_8.name()), System.err);
I will change it to default Charset,

2021-01-18 13:18 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/output/FileOutputService.java
> +    super(new PrintStream(path.toString(), Charset.defaultCharset().name()), System.err);
@chrisdennis : is it right also to use the default charset ? Charset could be changed by user per terminal also...

2021-01-18 13:19 UTC, mathieucarbou approved these changes

2021-01-18 13:24 UTC, mathieucarbou requested changes
In loadTopologyFromConfig(): use output.info
In loadTopologyFromNode(): use output.info
(see message)

2021-01-18 13:24 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
>    private Optional<Cluster> loadTopologyFromConfig() {
@mobasherul : this change is missing

2021-01-18 13:26 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ActivateAction.java
> +    output.println("Command successful!");
stderr yes as discussed 👍

2021-01-18 13:39 UTC, mathieucarbou approved these changes

2021-01-19 22:01 UTC, merged