TDB-5263 Modified/simplified Settings & Requirements
Terracotta-OSS/terracotta-platform pull request #925
Opened 2021-01-08 21:11 UTC by tmesic99

1. Added support for updating certain settings which do not require that ALL nodes be alive.  The affected settings are: backup-dir, security-dir and auditlog-dir.
2. Changed requirement name from ALL_NODES_ONLINE to CLUSTER_ONLINE.
3. Removed CLUSTER_ONLINE from backup-dir and data-dirs
4. Removed CLUSTER_RESTART from security-dir and auditlog-dir

Once this PR is merged it will be followed with EE system tests that exercise the above backup-dir and security-related settings.

2021-01-19 01:06 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +    }
👍

2021-01-19 01:07 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Requirement.java
> +   * APPLY TO CLUSTER-WIDE SETTING ONLY
👍

2021-01-19 01:07 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Requirement.java
> +  CLUSTER_ONLINE,
👍

2021-01-19 01:07 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Requirement.java
> +  NODE_RESTART,
👍

2021-01-19 01:20 UTC, mathieucarbou requested changes

2021-01-19 01:20 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +    }
@tmesic99 : could you please add a test for that ?

2021-01-20 18:10 UTC, tmesic99 commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +    }
Since the specific settings that were updated to support the unset command are enterprise settings (i.e. backup-dir, security), I'll add the system test to enterprise after we merge these changes into platform.  Is that ok?

2021-01-20 21:58 UTC, mathieucarbou requested changes

2021-01-20 21:58 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +    }
I think we should be able to update a node data directory too, to change the location on an existing one. So you can add some tests with node data directories

2021-01-20 21:58 UTC, mathieucarbou commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/model/ClusterTest.java
> +    assertTrue(updatedReconnectWindow == defaultReconnectWindow);
you should use `assertEquals`

2021-01-20 21:58 UTC, mathieucarbou commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/model/ClusterTest.java
> +    assertTrue(updatedWhitelist == defaultWhitelist);
same here

2021-01-20 21:58 UTC, mathieucarbou commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/model/ClusterTest.java
> +    assertFalse(cluster.equals(workingCluster));
can you also add a test that removes the value (workingCluster.setClientReconnectWindow(null) and verify that both clusters are now back to equality ?

2021-01-21 14:07 UTC, mathieucarbou commented on dynamic-config/cli/dynamic-config-cli-api/src/main/java/org/terracotta/dynamic_config/cli/api/command/ConfigurationMutationAction.java
> +    }
as discussed, will be done later in another PR

2021-01-21 14:09 UTC, mathieucarbou requested changes

2021-01-21 14:09 UTC, mathieucarbou commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/model/ClusterTest.java
> +  {
please reformat the source files

2021-01-21 16:33 UTC, mathieucarbou approved these changes

2021-01-21 16:33 UTC, merged