Enhanced error message when attempting secured/unsecured connections
Terracotta-OSS/terracotta-platform pull request #926
Opened 2021-01-19 17:57 UTC by tmesic99

For TDB-5163:
All Config Tool client->server commands utilize DiagnosticServiceProvider.fetchDiagnosticService
which in turn calls DiagnosticServiceFactory.fetch
which in turn calls ConnectionFactory.connect
which throws the 'handshake failed' exception.  
DiagnosticServiceProvider.fetchDiagnosticService is the first opportunity for the client to catch the exception - hence the change.  Let me know if there is a better place to inject this exception logic.

2021-01-19 18:10 UTC, mathieucarbou requested changes

2021-01-19 18:10 UTC, mathieucarbou commented on diagnostic/client/src/main/java/org/terracotta/diagnostic/client/connection/DiagnosticServiceProvider.java
> +        {
needs a reformat

2021-01-19 18:10 UTC, mathieucarbou commented on diagnostic/client/src/main/java/org/terracotta/diagnostic/client/connection/DiagnosticServiceProvider.java
> +      if (e.getMessage().contains("Client was able to establish connection with server but handshake with server failed")) {
This is one way to solve the issue, which is also used at another place.

But I am wondering if it is the right way to fix that, because the exception message could be changed in EE without us knowing.

In EE, we are using a `EnterpriseDiagnosticProvider` which overrides the OSS one. The original idea was to have this sort of code in EE in EnterpriseDiagnosticProvider.

Also, the advantage of using the EnterpriseDiagnosticProvider is that we have access to the SecurityException class that is thrown and contain the message you are checking.

2021-01-19 18:10 UTC, mathieucarbou commented on diagnostic/client/src/main/java/org/terracotta/diagnostic/client/connection/DiagnosticServiceProvider.java
> +      if (e.getMessage().contains("Client was able to establish connection with server but handshake with server failed")) {
@mobasherul : WDYT ?

2021-01-19 20:42 UTC, tmesic99 commented on diagnostic/client/src/main/java/org/terracotta/diagnostic/client/connection/DiagnosticServiceProvider.java
> +      if (e.getMessage().contains("Client was able to establish connection with server but handshake with server failed")) {
@mathieucarbou: I moved that same code block to the EnterpriseDiagnosticService and it behaves essentially the same way (but it's still using the approach to match the exception message - not ideal, I totally agree).
But note that the 'handshake failure' gets thrown initially by core as a RuntimeException and gets rethrown as just an Exception.  As far as I can see, there are no SecurityException being used anywhere (which is why I did the string message match).  Maybe I'm missing that.

2021-01-19 21:57 UTC, mathieucarbou commented on diagnostic/client/src/main/java/org/terracotta/diagnostic/client/connection/DiagnosticServiceProvider.java
> +      if (e.getMessage().contains("Client was able to establish connection with server but handshake with server failed")) {
ok. Let's look at that tomorrow morning with @mobasherul. There is an `ExceptionUtils` class tha twe can use for that I think that already contains some logic.

2021-01-21 17:21 UTC, tmesic99 commented
Closing PR.  Implementation will be done in EE.

2021-01-21 17:21 UTC, closed without merging