[DO NOT MERGE] Switch tests to inline servers where possible
Terracotta-OSS/terracotta-platform pull request #956
Opened 2021-03-02 20:27 UTC by myronkscott

2021-03-11 19:49 UTC, mathieucarbou requested changes
@myronkscott : please do not forget to reorganize imports and format code for the updated files :-)

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/ConfigurationGeneratorVisitor.java
> +    return configPath != null ? pathResolver.resolve(Paths.get(configPath)) : Setting.NODE_CONFIG_DIR.<RawPath>getDefaultValue().toPath();
I an not sure this is right: either the resolving + substitution should apply to the whole returned value or non. Here the default value is not considered.

`pathResolver.resolve(configPath != null ? Paths.get(configPath) : Setting.NODE_CONFIG_DIR.<RawPath>getDefaultValue().toPath();)`

Callers of this method also could be updated because they are substituting again.

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/StartupConfiguration.java
> +    this.groupPortMapper = mapper;
Why we cannot anymore use `ManagedServiceLoader.loadServices()` ?

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/parsing/OptionsParsingImpl.java
> +                "'%s' parameter can only be used with '%s', '%s', %s', '%s', '%s' and '%s' parameters",
we can rollback here: this message is displayed to the user and server-home is hidden

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/parsing/deprecated/DeprecatedOptionsParsingImpl.java
> +                "'%s' parameter can only be used with '%s', '%s', '%s', '%s', '%s' and '%s' parameters",
to rollback because we shouldn't let the user know this option is there

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/sync/DynamicConfigNomadSynchronizer.java
> +import org.terracotta.server.ServerEnv;
unused

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/sync/DynamicConfigNomadSynchronizer.java
> +          });
why this change ?

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/DefaultDiagnosticServices.java
> +    ServerEnv.getServer().getManagement().registerMBean(name, mBean);
could you please add a private final field Server and inject the Server by constructor to not rely on static mocking which dos not help parallelizing test ?

There are already example of that with the `NomadServerManager` to avoid relying on the static `ServerEnv` class

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/DefaultDiagnosticServices.java
> +      ServerEnv.getServer().getManagement().getMBeanServer().unregisterMBean(beanName);
could you please add a private final field Server and inject the Server by constructor to not rely on static mocking which dos not help parallelizing test ?

There are already example of that with the `NomadServerManager` to avoid relying on the static `ServerEnv` class

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/extensions/LogicalServerStateMBeanImpl.java
> +    ServerEnv.getServer().getManagement().registerMBean(MBEAN_LOGICAL_SERVER_STATE, this);
no need for such static access: the service is already injected by constructor

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/extensions/LogicalServerStateMBeanImpl.java
> +      Set<ObjectInstance> matchingBeans = ServerEnv.getServer().getManagement().getMBeanServer().queryMBeans(
no need for such static access - service already inject by constructor

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/test/java/org/terracotta/diagnostic/server/DefaultDiagnosticServicesRegistrationTest.java
> +    ServerEnv.setServer(server);
please remove the static mocking... it ides not help running tests concurrently in same vm and this is not needed. It also introduce a big coupling regarding how the tested class works inside.

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/test/java/org/terracotta/diagnostic/server/DefaultDiagnosticServicesRegistrationTest.java
> +        () -> ServerEnv.getServer().getManagement().getMBeanServer().getMBeanInfo(ServerMBean.createMBeanName("s2")),
no need for static access

2021-03-11 19:49 UTC, mathieucarbou commented on diagnostic/service/src/test/java/org/terracotta/diagnostic/server/DefaultDiagnosticServicesRegistrationTest.java
> +        () -> ServerEnv.getServer().getManagement().getMBeanServer().getMBeanInfo(ServerMBean.createMBeanName("AnotherName")),
no need for static access

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/entities/nomad-entity/server/src/main/java/org/terracotta/nomad/entity/server/NomadPassiveServerEntity.java
> +  private final Server server = ServerEnv.getServer();
please inject by constructor like it is done for other services

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/entities/nomad-entity/server/src/main/java/org/terracotta/nomad/entity/server/NomadPassiveServerEntity.java
> +  private final Server server = ServerEnv.getServer();
Also, in case of entities, the `Server` interface could be made available for services and entities at the ConfigurationProvider level to avoid any static call at all and going through teh service locator instead.

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/entities/nomad-entity/server/src/main/java/org/terracotta/nomad/entity/server/NomadServerEntityService.java
> +      return new NomadPassiveServerEntity<>(nomadServer);
I would have the `Server` injected here instead of `platformService` before, ideally Server being fetched from the registry. We can expose it through `DynamicConfigServiceProvider`

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/nomad/processor/NodeAdditionNomadChangeProcessor.java
> +  private final MBeanServer mbeanServer = ServerEnv.getServer().getManagement().getMBeanServer();
no static call : can be injected through constructor. Besides, `NomadServerManager` which is instantiating this class already has a ref to the server.

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/nomad/processor/NodeRemovalNomadChangeProcessor.java
> +  private final MBeanServer mbeanServer = ServerEnv.getServer().getManagement().getMBeanServer();
no static call : can be injected through constructor. Besides, `NomadServerManager` which is instantiating this class already has a ref to the server.

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/parsing/deprecated/DeprecatedOptionsParsingImpl.java
> +
the deprecated classes are for the old unsupported options... We shouldn't update them now.

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/test/java/org/terracotta/dynamic_config/server/configuration/service/DesynchronizedNomadConfigTest.java
> +
no need for static mocking... Server is already mocked line 448 and this is the ONLY place it has to be mocked. After that, the `NomadServerManager` can propagate this service to the classes it instantiates.

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/testing/entity/src/main/java/org/terracotta/dynamic_config/test_support/processor/MyDummyNomadAdditionChangeProcessor.java
> +
extra spaces

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/testing/entity/src/main/java/org/terracotta/dynamic_config/test_support/processor/ServerCrasher.java
> +    System.exit(99);
we shouldn't have a call to  `stopPlatform()` like before instead here too keep the old behaviour without inline ? 
Won't System.exit() retart  the node because of the loop in the script ?

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/ClusterDefinition.java
> +  boolean inlineServers() default true;
👍 nice to have it customizable there!

2021-03-11 19:49 UTC, mathieucarbou commented on dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java
> +  protected final ConfigurationContext createConfigurationContext(int stripes, int nodesPerStripe, boolean netDisruptionEnabled, boolean inlineServers) {
are you sure about adding final here ? Wonder about EE...

2021-03-11 19:56 UTC, myronkscott commented on dynamic-config/testing/entity/src/main/java/org/terracotta/dynamic_config/test_support/processor/ServerCrasher.java
> +    System.exit(99);
this kills the server without the cleanup code now associated with stop.  the server will not restart unless given a specific exit code(11)

2021-03-11 20:59 UTC, mathieucarbou commented on diagnostic/client/src/main/java/org/terracotta/diagnostic/client/DiagnosticServiceImpl.java
> +      throw new DiagnosticConnectionException();
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:06 UTC, mathieucarbou commented on common/json-support/src/test/java/org/terracotta/json/PathTest.java
> +import org.junit.Ignore;
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:06 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      ()->System.getProperty("user.dir"),
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:06 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +  SERVER_HOME(SettingName.SERVER_HOME,
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:06 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      ),
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:08 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +      Path baseDir = Paths.get(serverHome);
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:12 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/nomad/processor/NodeAdditionNomadChangeProcessor.java
> +    }
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:12 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/nomad/processor/NodeRemovalNomadChangeProcessor.java
> +    }
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:14 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/ConfigurationGeneratorVisitor.java
> +    return configPath != null ? pathResolver.resolve(Paths.get(configPath)) : Setting.NODE_CONFIG_DIR.<RawPath>getDefaultValue().toPath();
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:18 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/parsing/OptionsParsingImpl.java
> +                "'%s' parameter can only be used with '%s', '%s', %s', '%s', '%s' and '%s' parameters",
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:19 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/startup/parsing/deprecated/DeprecatedOptionsParsingImpl.java
> +                "'%s' parameter can only be used with '%s', '%s', '%s', '%s', '%s' and '%s' parameters",
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:20 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/sync/DynamicConfigNomadSynchronizer.java
> +import org.terracotta.server.ServerEnv;
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:20 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/sync/DynamicConfigNomadSynchronizer.java
> +          });
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:28 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/DefaultDiagnosticServices.java
> +    ServerEnv.getServer().getManagement().registerMBean(name, mBean);
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:28 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/DefaultDiagnosticServices.java
> +      ServerEnv.getServer().getManagement().getMBeanServer().unregisterMBean(beanName);
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:41 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/extensions/LogicalServerStateMBeanImpl.java
> +    ServerEnv.getServer().getManagement().registerMBean(MBEAN_LOGICAL_SERVER_STATE, this);
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:41 UTC, mathieucarbou commented on diagnostic/service/src/main/java/org/terracotta/diagnostic/server/extensions/LogicalServerStateMBeanImpl.java
> +      Set<ObjectInstance> matchingBeans = ServerEnv.getServer().getManagement().getMBeanServer().queryMBeans(
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:41 UTC, mathieucarbou commented on diagnostic/service/src/test/java/org/terracotta/diagnostic/server/DefaultDiagnosticServicesRegistrationTest.java
> +    ServerEnv.setServer(server);
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:41 UTC, mathieucarbou commented on diagnostic/service/src/test/java/org/terracotta/diagnostic/server/DefaultDiagnosticServicesRegistrationTest.java
> +        () -> ServerEnv.getServer().getManagement().getMBeanServer().getMBeanInfo(ServerMBean.createMBeanName("s2")),
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:41 UTC, mathieucarbou commented on diagnostic/service/src/test/java/org/terracotta/diagnostic/server/DefaultDiagnosticServicesRegistrationTest.java
> +        () -> ServerEnv.getServer().getManagement().getMBeanServer().getMBeanInfo(ServerMBean.createMBeanName("AnotherName")),
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:53 UTC, mathieucarbou commented on dynamic-config/entities/nomad-entity/server/src/main/java/org/terracotta/nomad/entity/server/NomadPassiveServerEntity.java
> +  private final Server server = ServerEnv.getServer();
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:53 UTC, mathieucarbou commented on dynamic-config/entities/nomad-entity/server/src/main/java/org/terracotta/nomad/entity/server/NomadServerEntityService.java
> +      return new NomadPassiveServerEntity<>(nomadServer);
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:53 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/nomad/processor/NodeAdditionNomadChangeProcessor.java
> +  private final MBeanServer mbeanServer = ServerEnv.getServer().getManagement().getMBeanServer();
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:53 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/service/nomad/processor/NodeRemovalNomadChangeProcessor.java
> +  private final MBeanServer mbeanServer = ServerEnv.getServer().getManagement().getMBeanServer();
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:55 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/test/java/org/terracotta/dynamic_config/server/configuration/service/DesynchronizedNomadConfigTest.java
> +
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:56 UTC, mathieucarbou commented on dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java
> +  protected final ConfigurationContext createConfigurationContext(int stripes, int nodesPerStripe, boolean netDisruptionEnabled, boolean inlineServers) {
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:56 UTC, mathieucarbou commented on dynamic-config/testing/entity/src/main/java/org/terracotta/dynamic_config/test_support/processor/MyDummyNomadAdditionChangeProcessor.java
> +
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 21:58 UTC, myronkscott commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      ()->System.getProperty("user.dir"),
this is not always "user.dir".  This is here specifically to put each server away from user.dir and separate each server's config logs etc...(I'm assuming that what you mean by always)

2021-03-11 22:01 UTC, myronkscott commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      ()->System.getProperty("user.dir"),
https://github.com/Terracotta-OSS/angela/blob/master/common/src/main/java/org/terracotta/angela/common/distribution/Distribution107InlineController.java#L197-L210

2021-03-11 22:21 UTC, myronkscott commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      ()->System.getProperty("user.dir"),
Nvm. I think I understand the code better now

2021-03-11 22:55 UTC, mathieucarbou commented on diagnostic/model/src/main/java/org/terracotta/diagnostic/model/LogicalServerState.java
> +  DIAGNOSTIC("DIAGNOSTIC");
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-11 22:55 UTC, mathieucarbou commented on diagnostic/model/src/main/java/org/terracotta/diagnostic/model/LogicalServerState.java
> +      return LogicalServerState.STARTING;
https://github.com/mathieucarbou/terracotta-platform/tree/for-myron

2021-03-12 11:54 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/test/java/org/terracotta/dynamic_config/server/configuration/service/DesynchronizedNomadConfigTest.java
> +    ServerEnv.setDefaultServer(server);
forgot to remove this block - will do in another PR

2021-03-12 11:55 UTC, mathieucarbou approved these changes

2021-03-12 11:56 UTC, merged