[WIP] Data Dir changes
Terracotta-OSS/terracotta-platform pull request #970
Opened 2021-03-18 05:43 UTC by mobasherul

2021-03-18 14:43 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      of(NODE_RESTART, PRESENCE),
Add a task to our Documentation story (TDB-4806) to update the Config-Tool.adoc to reflect these updates.

2021-03-18 15:04 UTC, mathieucarbou commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/model/Setting.java
> +      of(NODE_RESTART, PRESENCE),
Wait... @mobasherul : `NODE_RESTART ` should not be added. When a requirement is added there, it is global to any change. For data-dir, it is OK to add a data-dir without restart. Only updating requires a restart (and this has to be handled with the new veto method). The code should be similar to backup-dir, which is a setting we can set and update, but not unset.

2021-03-18 22:18 UTC, mathieucarbou requested changes

2021-03-18 22:18 UTC, mathieucarbou commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/DataRootsDynamicConfigExtension.java
> +    if (Files.isReadable(substitutedPath.resolve(markFile))) {
if we have a marker file but it is not readable, we have to fail the server startup because if we start without the data it will mess up things ;-)

2021-03-18 22:18 UTC, mathieucarbou commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/DataRootsDynamicConfigExtension.java
> +        String line = Files.readAllLines(substitutedPath.resolve(markFile)).get(0);
the logic is wrong: there can be other files created between the time we have created the marker and the time the user restarts. Also, the user may have messed up things. So to prevent any problem, here is the logic we should apply:

* when the marker file is created, put inside the old location + the list of all files inside the old data dir (including sub folders)
* when starting:
  * first load the marker file, load the old location and verify that the old location contains __at least__ all the listed files in the marker file
  * if no, or if the old location does not exist => we fail the startup: it means we miss a file that has been deleted (by the user ?) and this is wrong
  * if the old location exist AND all the listed files in the marker file are there
    * we copy all the files from old to the new location: __we have to replace existing files__ because if the server crashes and restarts, we need to be able to resume. __Note__: we do not copy the list in the marker file: we copy the exact content from the old location (which might contain more than the marker file, __but not less__)
    * once the whole copy is done, we can remove the marker file (first) : if the server crashes before the removal, the operation will happen again and will work, if the server crashes after the removal of this file, that is ok we have everything we need
    * then we can delete the old location completely.

2021-03-18 22:18 UTC, mathieucarbou commented on dynamic-config/server/services/src/main/java/org/terracotta/dynamic_config/server/service/handler/MetaDataDirConfigChangeHandler.java
> +  public void validate(NodeContext baseConfig, Configuration change) throws InvalidConfigChangeException {
same comment for data dirs: 
- we need to check the rawpath, path, then substituted real path
- we need to write in the marker file the old location plus the list the whole folder content
- etc.

perhaps it could be worth factoring out some  utility class that would be responsible for the move, something like:

`new MoveOperation(Path destination).prepare(Path source)`
`new MoveOperation(Path destination).move()`

- MoveOperation is constructed with a destination folder
- it can prepare the marker file by specifying a source location
- it can run the move operation by checking the marker file which contains the source and checklist

2021-03-26 16:56 UTC, mathieucarbou requested changes

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +    Files.walk(sourcePath).forEach(path -> list.add(path.toString()));
file streams need to be closed:
```
try (Stream<Path> paths = Files.walk(...)) {
...
}
```

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +    Path mark = Files.createFile(destination.resolve(markFile));
we shouldn't fail if file exists. If file exists, we should truncate and re-use it. we need to make sure the user can "replay" a change again if it fails, partially prepared, etc.

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +  public void prepare(Path sourcePath) throws IOException {
I think we should do something like: `sourcePath = sourcePath.toRealPath()` right ?
Because pathResolver is just rebasing a path based on a working directory if the path is relative.
So I am wondering if the output of walk could produce in some cases a file with a list of path inside that are not absolute... This could happen if the base directory passed to the path resolver is not absolute, like: `./kit/server`.

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +        throw new RuntimeException("Server can't start up because of permission issues which can lead to data loss");
we should add more explanation: 
- this is when moving a data directory
- which data directory ?

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +              throw new UncheckedIOException(new IOException(path + " must be present"));
add better error message like: `Moving data directory from: {} to: {} failed because file: {} is not readable`

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +                throw new UncheckedIOException(ex);
add better error message like: `Moving data directory from: {} to: {} failed because file: {} cannot be copied. Error: {}`

2021-03-26 16:56 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +          String line = Files.readAllLines(mark).get(0);
just do only one `Files.readAllLines(mark)` and keep this list

2021-03-29 10:08 UTC, mobasherul commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +        throw new RuntimeException("Server can't start up because of permission issues which can lead to data loss");
Do we want to add info about specific data-drectory as this could happen due to metadata-dir as well

2021-03-29 10:09 UTC, mobasherul commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +        throw new RuntimeException("Server can't start up because of permission issues which can lead to data loss");
How about -> Server cannot startup because movement for one of the " +
            "existing data-dir or metadata-dir to new destination: " + destination +
            "cannot be completed because of permission issues");

2021-03-29 14:31 UTC, mobasherul commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +  public void prepare(Path sourcePath) throws IOException {
I am not sure if it can cause problem because whatever be the basepath for resolver, both the existing datadir path and newdatadir path are resolved from that same base path.

2021-03-29 16:07 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +  public void prepare(Path sourcePath) throws IOException {
yes you are right... forget about my comment ;-)

2021-03-29 16:07 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +        throw new RuntimeException("Server can't start up because of permission issues which can lead to data loss");
perfect!

2021-03-29 16:08 UTC, mathieucarbou commented on dynamic-config/server/server-api/src/main/java/org/terracotta/dynamic_config/server/api/MoveOperation.java
> +  public void prepare(Path sourcePath) throws IOException {
yes right! forget my comment

2021-03-29 16:11 UTC, mathieucarbou approved these changes

2021-04-08 06:13 UTC, closed without merging