Move to new tc-apis
Terracotta-OSS/terracotta-platform pull request #977
Opened 2021-03-23 22:34 UTC by myronkscott

Also a few cleanup items for testing.

2021-03-23 22:39 UTC, mathieucarbou approved these changes

2021-03-24 00:27 UTC, myronkscott commented
I think these tests are memory constrained causing failures on some machine above 4 parallel workers.

2021-03-24 01:29 UTC, mathieucarbou commented on management/testing/integration-tests/pom.xml
> +          <reuseForks>false</reuseForks>
👍

2021-03-24 13:01 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
this is already done [in the super class](https://github.com/Terracotta-OSS/terracotta-platform/blob/90b882a6161225b21856aa53c668eae53cae3ffe/dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java#L240-L245) when `autoStart` and `autoActivate` are both true.

2021-03-24 13:01 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
this is already done [in the super class](https://github.com/Terracotta-OSS/terracotta-platform/blob/90b882a6161225b21856aa53c668eae53cae3ffe/dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java#L240-L245) when `autoStart` and `autoActivate` are both true.

2021-03-24 13:01 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
this is already done [in the super class](https://github.com/Terracotta-OSS/terracotta-platform/blob/90b882a6161225b21856aa53c668eae53cae3ffe/dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java#L240-L245) when `autoStart` and `autoActivate` are both true.

2021-03-24 13:02 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
same

2021-03-24 13:02 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
same

2021-03-24 13:02 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
same

2021-03-24 13:02 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
same

2021-03-24 13:02 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
same

2021-03-24 13:03 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
same

2021-03-24 13:03 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    }, is(2));
some system out

2021-03-24 13:06 UTC, mathieucarbou requested changes
left some comments

2021-03-24 13:52 UTC, myronkscott commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
Was doing an experiment.  There has to be some race somewhere

2021-03-24 13:52 UTC, myronkscott commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    }, is(2));
Testing

2021-03-24 15:44 UTC, mathieucarbou approved these changes

2021-03-24 15:48 UTC, mathieucarbou commented on dynamic-config/testing/system-tests/src/test/java/org/terracotta/dynamic_config/system_tests/activated/DetachCommand1x2IT.java
> +    waitUntil(()->angela.tsa().getPassives().size(), is(1));
that, or it depends on the machine and time (busyness, slowness, lack of resources) ?
Because since my last commits and removal of this assert duration, I had more green builds than failed builds. 
But yesterday and today, more failures.
It's really random.

2021-03-24 16:00 UTC, merged