TDB-5082 New Config File Format
Terracotta-OSS/terracotta-platform pull request #982
Opened 2021-03-26 11:39 UTC by tmesic99

Note::
- import config file must end with .cfg.  Checks are done during import to check for .properties or .cfg and routed accordingly.
- default export output format is the new .cfg format: (cfg | propertes | json)
- input format accepts: [[stripe|node :]<stripe_or_node_name>:]<setting>=<value>
- output format always includes stripe|node scope

2021-03-29 13:59 UTC, tmesic99 commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/ExportCommand.java
> +  @Parameter(names = {"-outputformat"}, hidden = true, description = "Output type (cfg|properties|json). Default: config", converter = FormatConverter.class)
'Default: config' should be 'Default: cfg'

2021-03-29 14:04 UTC, tmesic99 commented on dynamic-config/cli/config-tool/src/main/java/org/terracotta/dynamic_config/cli/config_tool/parsing/deprecated/DeprecatedExportCommand.java
> +  @Parameter(names = {"-t"}, hidden = true, description = "Output type (cfg|properties|json). Default: config", converter = FormatConverter.class)
'Default: config' should be 'Default: cfg'

2021-03-29 14:07 UTC, tmesic99 commented on dynamic-config/cli/dynamic-config-cli-api/src/test/java/org/terracotta/dynamic_config/cli/api/command/ImportActionTest.java
> +    int[] ports = {9411, 9422, 9422};
Ports should be {9411, 9421, 9422}

2021-03-29 16:03 UTC, mathieucarbou requested changes

2021-03-29 16:03 UTC, mathieucarbou commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslatorTest.java
> +      "Node 'n1' has no settings assigned to it.  Add at least one setting or remove it from the appropriate '<stripe>:node-names' property",
I see a lot of double spaces - I think you should replace them all with single space to be comnsistent with all other messages.

2021-03-29 16:16 UTC, tmesic99 commented on dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java
> +      dest = getBaseDir().resolve(src.getFileName());
done

2021-03-29 16:18 UTC, tmesic99 commented on dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java
>        Files.createDirectories(getBaseDir());
done

2021-03-29 16:37 UTC, tmesic99 commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslatorTest.java
> +    assertThat(props.getProperty("stripe.1.node.1.backup-dir"), is("dir1"));
I recollect that there was no strong feeling either way (in-order vs scope-specific overrides).  So I kept the in-order implemenation.  I can certainly implement it either way.  
@jhouserizer:  for the new config file format, should a node's specific setting value (e.g. node1:backup-dir=unique_dir) override any occurrence of that same node's setting being indirectly set via a cluster or stripe-wide scope (e.g. backup-dir=... or stripe1:backup-dir=...?

2021-03-29 16:38 UTC, tmesic99 commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslatorTest.java
> +      "node.5.:port=7",
:)

2021-03-29 17:05 UTC, tmesic99 commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslatorTest.java
> +      "Node 'n1' has no settings assigned to it.  Add at least one setting or remove it from the appropriate '<stripe>:node-names' property",
done

2021-03-29 17:10 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +  public static final String ERR_NO_NODES_SPECIFIED_FOR_PROPERTY = "No nodes were specified for property ";
done

2021-03-29 17:21 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      props.entrySet().stream().forEach(e -> sortedProps.put(e.getKey().toString(), e.getValue().toString()));
done

2021-03-29 17:27 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      throw new UncheckedIOException("Failed to read configuration file: " + configFile.getFileName() + ". Make sure the file exists and is readable", e);
done

2021-03-29 17:29 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +    } catch (IOException e) {
done

2021-03-29 17:30 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      throw new UncheckedIOException("Failed to read configuration file: " + configFile.getFileName() + ". Make sure the file exists and is readable", e);
done

2021-03-29 17:34 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      reader.lines().forEach(line -> {
done

2021-03-29 17:41 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +          List<String> splits = Stream.of(line.split(EQUALS)).map(String::trim).collect(Collectors.toList());
done.

2021-03-29 17:46 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      });
done

2021-03-29 17:51 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +    }
I originally had it like that.  But then decided that I wanted all the errors to be prefixed with the message:
"Error(s) were found parsing the .cfg file:" which is added by addErrorAndThrow().

2021-03-29 18:12 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +    List<String> splits = Stream.of(nodeNamesProperty.split(COLON)).map(String::trim).collect(Collectors.toList());
done

2021-03-29 18:19 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +  private String validateNamespace(String stripeOrNodeName, String prop, String scope) throws IOException {
done

2021-03-29 18:30 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +        nodesNamespace.entrySet().stream()
done

2021-03-29 20:15 UTC, tmesic99 commented on dynamic-config/testing/support/src/main/java/org/terracotta/dynamic_config/test_support/DynamicConfigIT.java
> +      final String[] updated = {contents};
done

2021-03-30 12:49 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +  StringBuilder configFileOutput;
Will implement as 'not a service' and make suggested changes.

2021-03-30 12:49 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +  StringBuilder configFileOutput;
done

2021-03-30 13:46 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +    Map<String, String> props = new LinkedHashMap<>();
done

2021-03-30 17:12 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      addErrorAndThrow(ERR_STRIPE_NAMES_PROPERTY_MISSING);
done - implemented both methods as both were required

2021-03-30 17:22 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +      throw new UncheckedIOException(new IOException(error.toString()));
done

2021-03-30 17:23 UTC, tmesic99 commented on dynamic-config/model/src/main/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslator.java
> +  }
done

2021-03-31 14:57 UTC, tmesic99 commented on dynamic-config/model/src/test/java/org/terracotta/dynamic_config/api/service/ConfigPropertiesTranslatorTest.java
> +    assertThat(props.getProperty("stripe.1.node.1.backup-dir"), is("dir1"));
Confirmed with James that more specific scoped settings should always override their higher-scoped instances.  Now, the config file is processed in order of cluster-scope, stripe-scope then node-scope settings (instead of line-by-line order).

2021-04-06 18:44 UTC, mathieucarbou approved these changes

2021-04-06 18:44 UTC, merged