Fixing Data-Dir and MetaData-Dir update.
Terracotta-OSS/terracotta-platform pull request #990
Opened 2021-04-21 12:40 UTC by mobasherul

2021-04-21 12:41 UTC, mobasherul commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/DataDirConfigChangeHandler.java
> +        if (!isEmpty(substitutedDataDirPath)) {
This is required now if somebody is running all servers in same host and do something like set data-dir=main:<path> then it should fail otherwise subsequent nodes will overwrite the mark files we are writing in new path.

2021-04-21 13:11 UTC, mathieucarbou requested changes

2021-04-21 13:11 UTC, mathieucarbou commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/DataDirConfigChangeHandler.java
> +        if (!isEmpty(substitutedDataDirPath)) {
@mobasherul @tmesic99 @chrisdennis : regarding any validation / changes in the validate method: pay attention that a nomad change needs to be "replay-able" in case of partial prepare for example. If we require the `substitutedDataDirPath` to be empty, which is logical, how to handle the case where we have a partial prepare that is caused by a node crash at the time we do the `prepare()` ? 
In such case, the destination folder is created, the marker file is being written, but the node crashes, and the nomad transaction won't be repairable because this `validate()` method will always fail.

2021-04-22 13:58 UTC, chrisdennis commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/Utils.java
> +    return existing.startsWith(newPath) || newPath.startsWith(existing);
I think both of these needs to be converted to `toRealPath()` before this method will work correctly? In fact you may even need to be more exhaustive by actually resolving paths against the real filesystem otherwise you might get defeated by things like symlinks.

2021-04-22 13:58 UTC, chrisdennis commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/Utils.java
> +        return !directory.iterator().hasNext();
```java
return !directory.findAny().isPresent()
```
seems more Stream-like.

2021-04-22 16:57 UTC, mobasherul commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/Utils.java
> +    return existing.startsWith(newPath) || newPath.startsWith(existing);
Existing path resolver would already have resolved the paths according to base dir before passing the paths here but I am not sure whether that will work with symlinks.

2021-04-22 17:00 UTC, chrisdennis commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/Utils.java
> +    return existing.startsWith(newPath) || newPath.startsWith(existing);
```java
  public Path resolve(Path path) {
    if (path == null) {
      return null;
    }
    Path transformed = transform.apply(path);
    if (transformed.isAbsolute()) {
      return path; // keep original path and placeholders
    }
    return baseDir.resolve(path); // keep original path and placeholders
  }
```
Unless `baseDir` is absolute this doesn't necessarily return an absolute path.

Also... and absolute and a real path aren't the same thing (especially on case insensitive filesystems).

2021-04-22 19:26 UTC, mobasherul commented on data-root-resource/src/main/java/org/terracotta/config/data_roots/Utils.java
> +        return !directory.iterator().hasNext();
Its not a stream.

2021-04-23 14:24 UTC, mathieucarbou approved these changes

2021-04-23 14:24 UTC, merged