Usage info
Terracotta-OSS/terracotta-platform pull request #991
Opened 2021-04-22 13:09 UTC by myronkscott

fix test logging.

Provide usage info if requested

2021-04-22 13:15 UTC, chrisdennis approved these changes
Comments with approval... change what you wish.

2021-04-22 13:15 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +import java.util.concurrent.Callable;
imports in the wrong place.

2021-04-22 13:15 UTC, chrisdennis commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +  private void withMyClassLoader(Callable<Void> runnable) throws ConfigurationException {
It makes my brain itch that this isn't (but I can live with it):
```java
private <T> T withMyClassLoader(Callable<T> callable) throws Exception {
  ...
}
```

2021-04-22 13:29 UTC, myronkscott commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +  private void withMyClassLoader(Callable<Void> runnable) throws ConfigurationException {
fixed

2021-04-22 13:29 UTC, myronkscott commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +import java.util.concurrent.Callable;
fixed

2021-04-22 13:30 UTC, chrisdennis approved these changes

2021-04-22 16:28 UTC, mobasherul commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +  private void withMyClassLoader(Callable<Void> runnable) throws ConfigurationException {
It will throw an exception which will be printed on console as well which is not users will like when they run ./start-server.sh -help

2021-04-22 16:30 UTC, mobasherul commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +  private void withMyClassLoader(Callable<Void> runnable) throws ConfigurationException {
I think ConfigurationException should be catched to not let it display on console.

2021-04-22 19:10 UTC, myronkscott commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +  private void withMyClassLoader(Callable<Void> runnable) throws ConfigurationException {
Right now it is the only way to get the server to stop.  We will look into further fixes later.

2021-04-23 06:18 UTC, mobasherul approved these changes

2021-04-23 14:21 UTC, mathieucarbou requested changes

2021-04-23 14:21 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +      throw new ConfigurationException(e.getMessage(), e);
Can we catch before `ConfigurationException` instead of wrapping an already thrown `ConfigurationException` ? or do an `instanceof` ?

2021-04-23 14:21 UTC, mathieucarbou commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +      }
If the help is now completely controlled by DC, what is the need of having `String getConfigurationParamsDescription()` in the interface now ?

2021-04-23 18:15 UTC, myronkscott commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +      }
It's legacy.  If you want to return nothing there, that's fine.

2021-04-23 18:17 UTC, myronkscott commented on dynamic-config/server/configuration-provider/src/main/java/org/terracotta/dynamic_config/server/configuration/DynamicConfigConfigurationProvider.java
> +      throw new ConfigurationException(e.getMessage(), e);
fixed

2021-04-23 18:18 UTC, myronkscott commented
PR updated and rebased.  Printing of ConfiguratoinException will be addressed in pending core changes.

2021-04-23 18:28 UTC, mathieucarbou approved these changes

2021-04-23 19:05 UTC, mathieucarbou commented
MERGING. All PR builds were all green already.

2021-04-23 19:05 UTC, merged